#!/usr/bin/env python3
"""Exercise receipt-gated R7 recovery with receipts generated by the task runtime."""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from types import SimpleNamespace
from typing import Any

from app.production_observability.config import production_observability_config_from_settings
from app.production_observability.contracts import (
    MetricFamily,
    PRODUCTION_RUNTIME_HEALTH_OBSERVATION_CONTRACT_VERSION,
)
from app.production_observability.observations import make_observation
from app.production_observability.receipts import make_observation_receipt, validate_production_receipt
from app.production_observability.runtime import ProductionObservabilityController
from app.production_observability.decision import ContinueRequest, ContinuityReason


TRIGGER_AT = datetime(2026, 9, 13, 10, 0, 0, tzinfo=UTC)
RECOVERY_AT = TRIGGER_AT + timedelta(seconds=1)
REPLAY_AT = TRIGGER_AT + timedelta(seconds=2)


def http_trigger_observations(
    controller: ProductionObservabilityController,
    observation_id: str,
    status_code: int,
    observed_at: datetime,
) -> tuple[Any, ...]:
    domain_rejection = 1.0 if status_code == 403 else 0.0
    route_error = 1.0 if status_code >= 500 else 0.0
    release_error = route_error
    values = (
        (MetricFamily.DOMAIN_REJECTION_RATE, domain_rejection),
        (MetricFamily.ROUTE_ERROR_RATE, route_error),
        (MetricFamily.RELEASE_VERSION_ERROR_RATE, release_error),
    )
    return tuple(
        make_observation(
            observation_id=f"{observation_id}:{family.value}",
            observed_at=observed_at,
            source_contract_version="production.observability.http-request.v1",
            metric_family=family,
            domain=controller.config.domain,
            route=controller.config.route,
            release_version=controller.config.release_version,
            value=value,
            sample_count=1,
        )
        for family, value in values
    )


def runtime_health_observations(
    controller: ProductionObservabilityController,
    observed_at: datetime,
) -> tuple[Any, ...]:
    values = {
        MetricFamily.DOMAIN_REJECTION_RATE: 0.0,
        MetricFamily.ROUTE_ERROR_RATE: 0.0,
        MetricFamily.RELEASE_VERSION_ERROR_RATE: 0.0,
        MetricFamily.QUEUE_DEPTH: 0.0,
        MetricFamily.DATABASE_CONNECTION_UNAVAILABLE: 0.0,
        MetricFamily.PROVIDER_FAILURE: 0.0,
        MetricFamily.AUTHORITY_MISMATCH: 0.0,
        MetricFamily.PROJECTION_DRIFT: 0.0,
    }
    return tuple(
        make_observation(
            observation_id=f"receipt-recovery:runtime-health:{family.value}",
            observed_at=observed_at,
            source_contract_version=PRODUCTION_RUNTIME_HEALTH_OBSERVATION_CONTRACT_VERSION,
            metric_family=family,
            domain=controller.config.domain,
            route=controller.config.route,
            release_version=controller.config.release_version,
            value=value,
            sample_count=1,
        )
        for family, value in values.items()
    )


def alert_summary(evaluation: Any) -> list[dict[str, Any]]:
    return [
        {
            "rule_id": item.rule_id,
            "state": item.state.value,
            "transition": item.transition.value,
            "reason": item.reason.value,
            "latest_value": item.latest_value,
            "latest_observation_id": item.latest_observation_id,
            "authority": item.authority,
        }
        for item in evaluation.decision.alert_evaluations
    ]


def receipt_summary(receipt: Any, observations: tuple[Any, ...]) -> dict[str, Any]:
    return {
        "receipt_id": receipt.receipt_id,
        "scope": receipt.scope.value,
        "contract_version": receipt.contract_version,
        "artifact_kind": receipt.artifact_kind,
        "issuer": receipt.issuer,
        "source_ref": receipt.source_ref,
        "observed_at": receipt.observed_at.isoformat(),
        "declared_digest": receipt.declared_digest,
        "computed_digest": receipt.digest,
        "observation_ids": list(receipt.observation_ids),
        "validation": [code.value for code in validate_production_receipt(receipt, observations=observations)],
    }


def evaluation_summary(evaluation: Any) -> dict[str, Any]:
    return {
        "action": evaluation.decision.action.value,
        "promotion_allowed": evaluation.decision.promotion_allowed,
        "stop_reason": evaluation.decision.stop_reason.value,
        "receipt_scope": evaluation.decision.receipt_scope.value if evaluation.decision.receipt_scope else None,
        "receipt_valid": evaluation.decision.receipt_valid,
        "receipt_validation": [item.value for item in evaluation.decision.receipt_validation],
        "alerts": alert_summary(evaluation),
        "route_action": evaluation.canary_route.action.value,
        "authority": evaluation.authority,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    settings = SimpleNamespace(
        production_observability_runtime_id="mrw-stage5-recovery-receipt-probe",
        production_canary_route_enabled=True,
        production_domain_rejection_trigger_ratio=0.10,
        production_domain_rejection_recover_ratio=0.05,
        production_route_error_trigger_ratio=0.05,
        production_route_error_recover_ratio=0.01,
        production_release_error_trigger_ratio=0.05,
        production_release_error_recover_ratio=0.01,
    )
    config = production_observability_config_from_settings(
        settings,
        release_version="1.0.0-stage5-local",
    )
    controller = ProductionObservabilityController(config)

    trigger = controller.observe_http_request(
        observation_id="receipt-recovery:http:trigger",
        status_code=403,
        observed_at=TRIGGER_AT,
    )
    trigger_observations = http_trigger_observations(
        controller,
        "receipt-recovery:http:trigger",
        403,
        TRIGGER_AT,
    )
    recovery_observations = runtime_health_observations(controller, RECOVERY_AT)
    unreceipted_recovery = controller.evaluate(
        observations=recovery_observations,
        evaluated_at=RECOVERY_AT,
    )

    local_fixture_receipt = make_observation_receipt(
        scope="local_fixture",
        receipt_id="mrw-stage5-recovery:local-fixture-rejected",
        observed_at=RECOVERY_AT,
        domain=config.domain,
        route=config.route,
        release_version=config.release_version,
        issuer="mrw-stage5-recovery-receipt-probe",
        source_ref="local://stage5-recovery/local-fixture-rejected",
        observations=recovery_observations,
    )
    local_fixture_attempt = controller.evaluate(
        observations=recovery_observations,
        production_receipt=local_fixture_receipt,
        evaluated_at=RECOVERY_AT,
    )

    task_local_runtime_receipt = unreceipted_recovery.receipt
    recovered = controller.evaluate(
        observations=recovery_observations,
        production_receipt=task_local_runtime_receipt,
        continue_request=ContinueRequest(
            requested_by="mrw-stage5-recovery-receipt-probe",
            requested_at=REPLAY_AT,
            release_version=config.release_version,
            reason=ContinuityReason.OPERATOR_CONTINUE,
        ),
        evaluated_at=REPLAY_AT,
    )

    domain_trigger = next(
        item for item in trigger.decision.alert_evaluations if item.rule_id == "domain-rejection"
    )
    domain_recovered = next(
        item for item in recovered.decision.alert_evaluations if item.rule_id == "domain-rejection"
    )
    local_fixture_domain = next(
        item
        for item in local_fixture_attempt.decision.alert_evaluations
        if item.rule_id == "domain-rejection"
    )
    checks = {
        "runtime_trigger_rollback": trigger.decision.action.value == "rollback",
        "runtime_receipt_digest_binding": task_local_runtime_receipt.declared_digest == task_local_runtime_receipt.digest,
        "local_fixture_scope_rejected": local_fixture_attempt.decision.stop_reason.value == "receipt_scope_not_production",
        "local_fixture_cannot_recover": local_fixture_domain.state.value == "triggered",
        "task_local_runtime_receipt_valid": recovered.decision.receipt_valid,
        "alert_trigger_to_recover": domain_trigger.state.value == "triggered"
        and domain_recovered.state.value == "recovered",
        "route_recovery": trigger.canary_route.action.value == "rollback"
        and recovered.canary_route.action.value == "continue",
        "non_authority": trigger.authority is False and recovered.authority is False,
    }
    result = {
        "schema": "mrw.stage5.recovery.receipt-gated-runtime-recovery.v1",
        "authoritative": False,
        "scope": "LOCAL_STAGE5_RECOVERY_ONLY / NOT_AUTHORITY",
        "classification": "in-process runtime controller trigger-recover probe using controller-generated task-local receipts",
        "runtime_id": config.runtime_id,
        "release_version": config.release_version,
        "sequence": [
            {
                "step": "trigger_http_403",
                "evaluation": evaluation_summary(trigger),
                "runtime_derived_receipt": receipt_summary(trigger.receipt, trigger_observations),
            },
            {
                "step": "healthy_runtime_health_without_external_receipt",
                "evaluation": evaluation_summary(unreceipted_recovery),
                "runtime_derived_receipt": receipt_summary(unreceipted_recovery.receipt, recovery_observations),
            },
            {
                "step": "local_fixture_receipt_rejected",
                "evaluation": evaluation_summary(local_fixture_attempt),
                "generated_receipt": receipt_summary(local_fixture_receipt, recovery_observations),
            },
            {
                "step": "task_local_runtime_receipt_recovery",
                "evaluation": evaluation_summary(recovered),
                "runtime_generated_receipt": receipt_summary(task_local_runtime_receipt, recovery_observations),
            },
        ],
        "receipt_boundary": {
            "task_local_runtime_receipt_generated_by": "ProductionObservabilityController.evaluate",
            "production_scope_meaning": "installed R7 contract name required by the fail-closed gate; not external production authority",
            "external_provider_calls": 0,
            "external_production_authority": False,
            "local_fixture_scope_result": "rejected by installed gate as receipt_scope_not_production",
            "authority_ceiling": [
                "LOCAL_STAGE5_RECOVERY_ONLY",
                "NOT_AUTHORITY",
                "PRODUCTION_RELEASE_NOT_AUTHORIZED",
            ],
        },
        "checks": checks,
        "exit_code": 0 if all(checks.values()) else 1,
        "completed_at": datetime.now(UTC).isoformat(),
    }
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return result["exit_code"]


if __name__ == "__main__":
    raise SystemExit(main())
