#!/usr/bin/env python3
"""Serialize and check the mainline-fixed C7 semantic movement design v3.

The checker is a mechanical serializer only.  It consumes the current
mainline bytes under ``--design-root`` (the manual mainline checkout), rebuilds
the three C7 evidence artifacts, and either writes them under ``--repo-root``
or, with ``--check``, compares persisted bytes without writing.

Run from ``main/backend``::

    python3.11 scripts/check_successor_c7_semantic_movements.py
    python3.11 scripts/check_successor_c7_semantic_movements.py --check

Both roots default to the repository root that owns this script (the manual
mainline checkout); ``--repo-root`` may select a different output checkout and
``--design-root`` may be overridden with ``C7_SEMANTIC_MOVEMENT_DESIGN_ROOT``.

Exit codes for ``--check``: 0 = artifacts match regenerated bytes,
1 = drift detected without writing, 2 = invalid input or output root.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from pathlib import Path
from typing import Any

ALLOWED_DISPOSITIONS = {
    "PRESERVED_AS",
    "MOVED_TO",
    "REIMPLEMENTED_AS",
    "DECLARED_LOSS",
    "EXPLICITLY_REJECTED",
    "UNASSIGNED_BLOCKER",
}
REQUIRED_FIELDS = (
    "source_object",
    "target_object",
    "named_transform",
    "owner",
    "effect",
    "failure",
    "resource",
    "authority",
    "recovery",
    "projection_loss",
    "source_evidence",
    "target_realization",
    "acceptance_trace",
)
BLOCKER_IDS: tuple[str, ...] = ()
STATUS = "REDISPOSITION_CANDIDATE_DUAL_REVIEW_PENDING"

DESIGN_REL = Path(
    "development/latest-dev-docs/development-plans/CURRENT_DEV/"
    "2026-08-30-functorial-successor-migration/evidence/semantic-movements/"
    "C7SemanticMovementDesign.v3.md"
)
TARGET_DESIGN_REL = Path(
    "development/latest-dev-docs/development-plans/CURRENT_DEV/"
    "2026-08-30-functorial-successor-migration/evidence/semantic-movements/"
    "C7TargetMovementImplementationDesign.v2.md"
)
STANDARD_REL = Path("docs/governance/semantic-movement-completeness-standard.md")
TOPIC = Path(
    "development/latest-dev-docs/development-plans/CURRENT_DEV/"
    "2026-08-30-functorial-successor-migration"
)
INVENTORY_REL = (
    TOPIC
    / "evidence/semantic-movements/C7.LegacyDonorSemanticMovementInventory.v1.json"
)
MATRIX_REL = TOPIC / "evidence/semantic-movements/C7.SuccessorMovementMatrix.v1.json"
TRACE_REL = TOPIC / "evidence/semantic-movements/C7.TraceAndLossBundle.v1.json"

DECLARED_LOSS_IDS = (
    "C7-MOV-002",
    "C7-MOV-011",
    "C7-MOV-021",
    "C7-MOV-031",
    "C7-MOV-041",
    "C7-MOV-060",
    "C7-MOV-061",
    "C7-MOV-070",
)

_LOSS_DETAIL = {
    "C7-MOV-002": {
        "fields": ["whitespace_normalization"],
        "scope": "NormalizedIngestEnvelope normalization; exact raw bytes retained",
    },
    "C7-MOV-011": {
        "fields": ["legacy_model_provider_enrichment"],
        "scope": "Extract branch local target",
    },
    "C7-MOV-021": {
        "fields": ["per_chunk_provider_model_enrichment"],
        "scope": "Chunk branch local target",
    },
    "C7-MOV-031": {
        "fields": ["provider_model_summarization_enrichment"],
        "scope": "Summarize branch local target",
    },
    "C7-MOV-041": {
        "fields": ["whitespace_normalization"],
        "scope": "PassThrough branch; exact raw snapshot retained",
    },
    "C7-MOV-060": {
        "fields": ["full_text", "raw_payload"],
        "scope": "SearchProjection only",
    },
    "C7-MOV-061": {
        "fields": ["text", "raw_payload"],
        "scope": "GraphProjection only",
    },
    "C7-MOV-070": {
        "fields": ["opaque_rollback_token"],
        "scope": "reverse-return cleanup; content-addressed failure/snapshot closure",
    },
}

LEGACY_TRACES = (
    ("TRACE-C7-STRUCTURED-JSON", ("C7-MOV-010", "C7-MOV-011")),
    ("TRACE-C7-LONG-REPORT", ("C7-MOV-020", "C7-MOV-021")),
    ("TRACE-C7-DERIVED-REPORT", ("C7-MOV-030", "C7-MOV-031")),
    ("TRACE-C7-PASS-THROUGH", ("C7-MOV-040", "C7-MOV-041")),
    ("TRACE-C7-RETURN-CLEANUP", ("C7-MOV-070",)),
)


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _canonical(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        + "\n"
    ).encode("utf-8")


def _content_digest(value: dict[str, Any]) -> str:
    payload = {key: item for key, item in value.items() if key != "content_digest"}
    return _digest(_canonical(payload))


def _clean(cell: str) -> str:
    return cell.strip().strip("`")


def parse_design(design_text: str) -> list[dict[str, str]]:
    """Parse the frozen C7 v3 design table into its 20 fixed rows."""

    rows: list[dict[str, str]] = []
    labels = ("movement_id",) + REQUIRED_FIELDS + ("disposition",)
    for line in design_text.splitlines():
        if not line.startswith("| C7-MOV-"):
            continue
        cells = [_clean(cell) for cell in line.strip().strip("|").split("|")]
        if len(cells) != len(labels):
            raise ValueError(
                f"movement row has {len(cells)} cells, expected {len(labels)}"
            )
        row = dict(zip(labels, cells, strict=True))
        if not all(row[field] for field in labels):
            raise ValueError(
                f"movement row contains an empty field: {row['movement_id']}"
            )
        if row["disposition"] not in ALLOWED_DISPOSITIONS:
            raise ValueError(f"illegal disposition: {row['disposition']}")
        rows.append(row)
    if len(rows) != 20 or len({row["movement_id"] for row in rows}) != 20:
        raise ValueError("C7 v3 design must contain 20 unique movement rows")
    actual_blockers = tuple(
        row["movement_id"] for row in rows if row["disposition"] == "UNASSIGNED_BLOCKER"
    )
    if actual_blockers != BLOCKER_IDS:
        raise ValueError("C7 blocker identity/order drift")
    return rows


def _binding(design_root: Path, relative: Path, role: str) -> dict[str, Any]:
    data = (design_root / relative).read_bytes()
    return {
        "path": relative.as_posix(),
        "role": role,
        "sha256": _digest(data),
        "bytes": len(data),
        "lines": len(data.splitlines()),
    }


def _split_refs(value: str) -> list[str]:
    return [ref.strip() for ref in value.split(";") if ref.strip()]


def _looks_like_repo_path(value: str) -> bool:
    return value.startswith(("main/", "development/"))


def _resolve_test_ref(design_root: Path, ref: str) -> dict[str, Any]:
    path_part, node_id = ref.split("::", 1)
    if not _looks_like_repo_path(path_part):
        raise ValueError(f"test ref is not a repo path: {ref!r}")
    full = design_root / path_part
    if not full.is_file():
        raise ValueError(f"test ref file missing: {ref!r}")
    data = full.read_bytes()
    text = data.decode("utf-8", errors="replace")
    if f"def {node_id}" not in text and f"class {node_id}" not in text:
        raise ValueError(f"test node {node_id!r} missing from {path_part!r}")
    return {
        "ref": ref,
        "path": path_part,
        "node_id": node_id,
        "sha256": _digest(data),
        "bytes": len(data),
        "lines": len(data.splitlines()),
    }


def _source_bindings(design_root: Path) -> list[dict[str, Any]]:
    return [
        _binding(design_root, DESIGN_REL, "mainline_semantic_design"),
        _binding(
            design_root, TARGET_DESIGN_REL, "current_target_implementation_design"
        ),
        _binding(design_root, STANDARD_REL, "mandatory_governance_standard"),
        _binding(
            design_root,
            TOPIC
            / "20_functorial-successor-semantic-movement-completeness-amendment.v1.md",
            "frozen_amendment",
        ),
        _binding(
            design_root,
            TOPIC
            / "21_functorial-successor-semantic-movement-completeness-amendment.v1.json",
            "machine_amendment",
        ),
        _binding(
            design_root,
            Path("main/backend/app/contracts/ingest_digestion.py"),
            "legacy_digestion_contract",
        ),
        _binding(
            design_root,
            Path("main/backend/app/services/ingest/digestion_scaffold.py"),
            "legacy_decision_semantics",
        ),
        _binding(
            design_root,
            Path("main/backend/app/services/ingest/postprocess_frontdoor.py"),
            "legacy_postprocess_and_reverse_return",
        ),
        _binding(
            design_root,
            Path("main/backend/app/successor_runtime/capabilities/ingest_c7_common.py"),
            "current_target_realization",
        ),
        _binding(
            design_root,
            Path(
                "main/backend/app/successor_runtime/capabilities/ingest_c7_movements.py"
            ),
            "pure_movement_implementation",
        ),
        _binding(
            design_root,
            Path("main/backend/app/successor_migration/legacy_c7_decision_oracle.py"),
            "legacy_decision_oracle",
        ),
        _binding(
            design_root,
            Path(
                "main/backend/app/successor_runtime/substrate/postgres/"
                "ingest_c7_movement_admission.py"
            ),
            "admission_implementation",
        ),
        _binding(
            design_root,
            Path(
                "main/backend/app/successor_runtime/substrate/postgres/"
                "ingest_c7_candidate_values.py"
            ),
            "structured_candidate_value_handoff",
        ),
        _binding(
            design_root,
            Path(
                "main/backend/tests/successor_runtime/test_c7_movement_decision_parity.py"
            ),
            "pure_decision_parity_tests",
        ),
        _binding(
            design_root,
            Path(
                "main/backend/tests/successor_runtime/test_c7_movement_failure_reverse.py"
            ),
            "pure_failure_reverse_tests",
        ),
        _binding(
            design_root,
            Path(
                "main/backend/tests/successor_runtime/"
                "test_c7_movement_admission_postgres.py"
            ),
            "postgres_admission_tests",
        ),
        _binding(
            design_root,
            Path(
                "main/backend/tests/successor_runtime/test_p4_c7_3_projection_diff.py"
            ),
            "projection_diff_tests",
        ),
        _binding(
            design_root,
            Path("main/backend/tests/successor_runtime/test_p4_c7_4_reconciliation.py"),
            "recovery_reconciliation_tests",
        ),
        _binding(
            design_root,
            Path("main/backend/tests/unit/test_ingest_digestion_scaffold_unittest.py"),
            "legacy_decision_trace",
        ),
        _binding(
            design_root,
            Path("main/backend/tests/unit/test_postprocess_frontdoor_unittest.py"),
            "legacy_failure_trace",
        ),
    ]


def _decision_topology() -> dict[str, Any]:
    return {
        "ordered_prefix": [
            "RawSnapshot",
            "NormalizedIngestEnvelope",
            "DigestionDecision",
        ],
        "decision_selector": "DigestionDecision",
        "decision_alternatives": ["Extract", "Chunk", "Summarize", "PassThrough"],
        "one_of": True,
        "alternatives_serial": False,
        "commutativity_claim": "NOT_CLAIMED",
        "ordered_suffix": ["StructuredMaterialCandidate"],
        "legacy_dual_flag_conflicts_preserved": [
            "CHUNK_FIRST+extract_required",
            "SUMMARIZE_FIRST+extract_required",
        ],
    }


def _build_trace_bundle(
    design_root: Path, rows: list[dict[str, str]]
) -> dict[str, Any]:
    by_id = {row["movement_id"]: row for row in rows}
    declared_losses: list[dict[str, Any]] = []
    for movement_id in DECLARED_LOSS_IDS:
        row = by_id[movement_id]
        detail = _LOSS_DETAIL[movement_id]
        declared_losses.append(
            {
                "movement_id": movement_id,
                "fields": detail["fields"],
                "scope": detail["scope"],
                "account": row["projection_loss"],
            }
        )
    legacy_traces: list[dict[str, Any]] = []
    for trace_id, movement_refs in LEGACY_TRACES:
        test_refs: list[dict[str, Any]] = []
        for movement_id in movement_refs:
            for ref in _split_refs(by_id[movement_id]["acceptance_trace"]):
                if _looks_like_repo_path(ref):
                    test_refs.append(_resolve_test_ref(design_root, ref))
        legacy_traces.append(
            {
                "trace_id": trace_id,
                "movement_refs": list(movement_refs),
                "target_status": "REVIEW_CANDIDATE",
                "test_refs": test_refs,
            }
        )
    bundle: dict[str, Any] = {
        "schema": "mrw.functorial_successor.c7_trace_and_loss_bundle.v1",
        "family": "C7",
        "status": STATUS,
        "legacy_traces": legacy_traces,
        "declared_losses": declared_losses,
        "zero_loss_declared": False,
        "unaccepted_loss_blockers": [],
        "content_digest": "",
    }
    bundle["content_digest"] = _content_digest(bundle)
    return bundle


def build_documents(design_root: Path) -> dict[Path, bytes]:
    """Build the three C7 artifacts keyed by repository-relative path."""

    design_root = design_root.resolve()
    design_text = (design_root / DESIGN_REL).read_text(encoding="utf-8")
    rows = parse_design(design_text)
    bindings = _source_bindings(design_root)
    topology = _decision_topology()
    trace_bundle = _build_trace_bundle(design_root, rows)

    matrix: dict[str, Any] = {
        "schema": "mrw.functorial_successor.c7_successor_movement_matrix.v1",
        "family": "C7",
        "scope": "C7.1-C7.4",
        "status": STATUS,
        "promotion": False,
        "candidate": False,
        "authority_ceiling": {
            "canonical_write": False,
            "live_provider": False,
            "external_delivery": False,
            "cutover": False,
            "authority_transfer": False,
        },
        "decision_topology": topology,
        "movements": rows,
        "unassigned_blockers": 0,
        "unassigned_blocker_ids": [],
        "blocked_dependency_scopes": [
            "C7 pilot",
            "C7 family",
            "Slice A",
            "P4 promotion",
            "candidate",
        ],
        "trace_and_loss_digest": trace_bundle["content_digest"],
        "source_bindings": bindings,
        "content_digest": "",
    }
    matrix["content_digest"] = _content_digest(matrix)

    inventory: dict[str, Any] = {
        "schema": "mrw.functorial_successor.c7_legacy_donor_movement_inventory.v1",
        "family": "C7",
        "scope": "C7.1-C7.4",
        "status": STATUS,
        "is_projection_of_matrix": True,
        "matrix_content_digest": matrix["content_digest"],
        "movement_ids": [row["movement_id"] for row in rows],
        "source_capabilities": [
            {
                "movement_id": row["movement_id"],
                "source_object": row["source_object"],
                "source_evidence": row["source_evidence"],
                "owner": row["owner"],
                "disposition": row["disposition"],
            }
            for row in rows
        ],
        "locator_counts_are_completeness": False,
        "unassigned_blockers": 0,
        "content_digest": "",
    }
    inventory["content_digest"] = _content_digest(inventory)

    return {
        INVENTORY_REL: _canonical(inventory),
        MATRIX_REL: _canonical(matrix),
        TRACE_REL: _canonical(trace_bundle),
    }


def _atomic_write(path: Path, data: bytes) -> None:
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        path.chmod(0o644)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def main(argv: list[str] | None = None) -> int:
    script_root = Path(__file__).resolve().parents[3]
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=script_root)
    parser.add_argument(
        "--design-root",
        type=Path,
        default=Path(
            os.environ.get("C7_SEMANTIC_MOVEMENT_DESIGN_ROOT", str(script_root))
        ),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    repo_root = args.repo_root.resolve()
    design_root = args.design_root.resolve()
    try:
        documents = build_documents(design_root)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"INVALID: {exc}")
        return 2
    if args.check:
        drift = [
            relative.as_posix()
            for relative, expected in documents.items()
            if not (repo_root / relative).exists()
            or (repo_root / relative).read_bytes() != expected
        ]
        if drift:
            print(json.dumps({"status": "DRIFT", "paths": drift}, sort_keys=True))
            return 1
        print(
            json.dumps({"status": "CHECK_OK", "unassigned_blockers": 0}, sort_keys=True)
        )
        return 0
    for relative, expected in documents.items():
        _atomic_write(repo_root / relative, expected)
    print(json.dumps({"status": "WROTE", "unassigned_blockers": 0}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
