#!/usr/bin/env python3
"""Deterministically generate the P1-P3 retrospective semantic movement backfill.

The generator consumes the mainline P1-P3 semantic-movement spec and the
independent C7 external design artifacts, then projects them into:

- evidence/semantic-movement/fragments/C1.v1.json ... C9.v1.json
- evidence/semantic-movement/P1P3LegacyDonorSemanticMovementInventory.v1.json
- evidence/semantic-movement/P1P3SuccessorMovementMatrix.v1.json
- evidence/semantic-movement/P1P3SemanticMovementGate.v1.json

It is a mechanical serializer only.  It never changes movement taxonomy,
dispositions, authority or promotion decisions, and it never writes to the
mainline spec, the C7 design artifacts, P1-P3 evidence or implementation.

Run from ``main/backend``::

    python3.11 scripts/generate_successor_p1_p3_semantic_movement.py
    python3.11 scripts/generate_successor_p1_p3_semantic_movement.py --check

``--repo-root`` selects the canonical evidence root that owns the mainline spec
and C7 design inputs; ``--output-root`` (default: ``--repo-root``) selects where
the generated artifacts are written or checked.  During integration both roots
are the repository root; a frozen input checkout may be used as ``--repo-root``
while this checkout receives the generated artifacts via ``--output-root``.

Exit codes for ``--check``: 0 = artifacts match regenerated bytes, 1 = drift
detected without writing, 2 = invalid input or output root.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from pathlib import Path
from typing import Any

ALLOWED_DISPOSITIONS = {
    "PRESERVED_AS",
    "MOVED_TO",
    "REIMPLEMENTED_AS",
    "DECLARED_LOSS",
    "EXPLICITLY_REJECTED",
    "UNASSIGNED_BLOCKER",
}
REQUIRED_FIELDS = (
    "source_object",
    "target_object",
    "named_transform",
    "owner",
    "effect",
    "failure",
    "resource",
    "authority",
    "recovery",
    "projection_loss",
    "source_evidence",
    "target_realization",
    "acceptance_trace",
)
FAMILIES = ("C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9")
INLINE_FAMILIES = ("C1", "C2", "C3", "C4", "C5", "C6", "C8", "C9")
P3_FRAGMENT_FAMILIES = ("C2", "C3", "C4", "C5", "C6")
C7_SCOPE = "C7.1-C7.4"
C7_BLOCKER_IDS = ()
C7_DESIGN_SHA256 = "43cf856369f2fd80b91b48233adcb718bca656b1500ce93737cdf1f567cfbbb8"
C7_INVENTORY_DIGEST = "4c92fef4f38ebe6b8d5ddf95771bc6b4b4da3ca132ac177cbeddea706ebe4bf8"
C7_MATRIX_DIGEST = "b4d15c086a2d9699061f934fc57880741f6959c939a7a493b0420fafc7fd05fd"
C7_TRACE_DIGEST = "2f1c0f179449b26ad1403cf6dda0034890b9020ccde4900ce4487e8ec485f92d"
SPEC_BYTES_SHA256 = "2a96bb63d0e3b548173558959da9fc4421024f300d9c39daf6dda5f7b79e53d2"

PLAN = Path(
    "development/latest-dev-docs/development-plans/CURRENT_DEV/"
    "2026-08-30-functorial-successor-migration"
)
SPEC_REL = PLAN / "evidence/semantic-movement/p1-p3-semantic-movement-spec.v1.json"
STANDARD_REL = Path("docs/governance/semantic-movement-completeness-standard.md")
AMENDMENT_MD_REL = (
    PLAN / "20_functorial-successor-semantic-movement-completeness-amendment.v1.md"
)
AMENDMENT_JSON_REL = (
    PLAN / "21_functorial-successor-semantic-movement-completeness-amendment.v1.json"
)
C7_DESIGN_REL = PLAN / "evidence/semantic-movements/C7SemanticMovementDesign.v3.md"
C7_INVENTORY_REL = (
    PLAN / "evidence/semantic-movements/C7.LegacyDonorSemanticMovementInventory.v1.json"
)
C7_MATRIX_REL = PLAN / "evidence/semantic-movements/C7.SuccessorMovementMatrix.v1.json"
C7_TRACE_REL = PLAN / "evidence/semantic-movements/C7.TraceAndLossBundle.v1.json"
P1_ELIGIBILITY_REL = PLAN / "evidence/P1FunctorizationEligibility.v1.json"
OWNER_INVENTORY_REL = (
    PLAN / "09_functorial-successor-f0-semantic-owner-inventory.v1.json"
)
P2V5_REL = PLAN / "evidence/P2C21CapabilityPacket.v5.json"
P3_AGGREGATE_REL = PLAN / "evidence/P3CapabilityMigration.v1.json"

FRAGMENT_REL = PLAN / "evidence/semantic-movement/fragments"
INVENTORY_REL = (
    PLAN / "evidence/semantic-movement/P1P3LegacyDonorSemanticMovementInventory.v1.json"
)
MATRIX_REL = PLAN / "evidence/semantic-movement/P1P3SuccessorMovementMatrix.v1.json"
GATE_REL = PLAN / "evidence/semantic-movement/P1P3SemanticMovementGate.v1.json"


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _canonical(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        + "\n"
    ).encode("utf-8")


def _content_digest(value: dict[str, Any]) -> str:
    payload = {key: item for key, item in value.items() if key != "content_digest"}
    return _sha256(_canonical(payload))


def _binding(repo_root: Path, relative: Path, role: str) -> dict[str, Any]:
    data = (repo_root / relative).read_bytes()
    return {
        "path": relative.as_posix(),
        "role": role,
        "sha256": _sha256(data),
        "bytes": len(data),
        "lines": len(data.splitlines()),
    }


def _load_json(repo_root: Path, relative: Path) -> Any:
    return json.loads((repo_root / relative).read_text(encoding="utf-8"))


def _clean(cell: str) -> str:
    return cell.strip().strip("`")


def parse_c7_design(design_text: str) -> list[dict[str, str]]:
    """Parse the frozen C7 v2 design table into its 20 fixed rows."""

    rows: list[dict[str, str]] = []
    labels = ("movement_id",) + REQUIRED_FIELDS + ("disposition",)
    for line in design_text.splitlines():
        if not line.startswith("| C7-MOV-"):
            continue
        cells = [_clean(cell) for cell in line.strip().strip("|").split("|")]
        if len(cells) != len(labels):
            raise ValueError(
                f"movement row has {len(cells)} cells, expected {len(labels)}"
            )
        row = dict(zip(labels, cells, strict=True))
        if not all(row[field] for field in labels):
            raise ValueError(
                f"movement row contains an empty field: {row['movement_id']}"
            )
        if row["disposition"] not in ALLOWED_DISPOSITIONS:
            raise ValueError(f"illegal disposition: {row['disposition']}")
        rows.append(row)
    if len(rows) != 20 or len({row["movement_id"] for row in rows}) != 20:
        raise ValueError("C7 v2 design must contain 20 unique movement rows")
    blockers = tuple(
        row["movement_id"] for row in rows if row["disposition"] == "UNASSIGNED_BLOCKER"
    )
    if blockers != C7_BLOCKER_IDS:
        raise ValueError("C7 blocker identity/order drift")
    return rows


def _resolve_json_pointer(doc: Any, pointer: str) -> tuple[bool, str]:
    if not pointer.startswith("/"):
        return False, "not a JSON pointer"
    tokens = pointer.split("/")[1:]
    current: Any = doc
    for token in tokens:
        token = token.replace("~1", "/").replace("~0", "~")
        if isinstance(current, dict):
            if token not in current:
                return False, f"pointer token {token!r} missing"
            current = current[token]
        elif isinstance(current, list):
            try:
                index = int(token)
            except ValueError:
                return False, f"pointer token {token!r} is not a list index"
            if index < 0 or index >= len(current):
                return False, f"pointer index {index} out of range"
            current = current[index]
        else:
            return False, f"cannot descend through {type(current).__name__}"
    return True, ""


def _resolve_fragment_selector(doc: Any, pointer: str) -> tuple[bool, str]:
    """Resolve p1-fragment style selectors such as C1.1 or C1.1.payload_schema."""

    current: Any | None = None
    remainder = ""
    if isinstance(doc, list):
        for item in doc:
            if not isinstance(item, dict) or "cell" not in item:
                continue
            cell = str(item["cell"])
            if pointer == cell:
                current = item
                break
            if pointer.startswith(cell + "."):
                current = item
                remainder = pointer[len(cell) + 1 :]
                break
        if current is None:
            return False, f"cell selector {pointer!r} missing from fragment"
    elif isinstance(doc, dict):
        if pointer in doc:
            current = doc[pointer]
        else:
            matches = [
                key for key in doc if pointer == key or pointer.startswith(key + ".")
            ]
            if not matches:
                return False, f"selector {pointer!r} missing from fragment"
            key = matches[0]
            current = doc[key]
            remainder = pointer[len(key) + 1 :]
    else:
        return False, f"selector {pointer!r} cannot resolve non-container fragment"
    if not remainder:
        return True, ""
    for token in remainder.split("."):
        if not isinstance(current, dict) or token not in current:
            return False, f"selector key {token!r} missing"
        current = current[token]
    return True, ""


def _resolve_pointer(doc: Any, pointer: str) -> tuple[bool, str]:
    if pointer.startswith("/"):
        return _resolve_json_pointer(doc, pointer)
    return _resolve_fragment_selector(doc, pointer)


_REPO_PATH_PREFIXES = (
    "main/",
    "development/",
    "docs/",
    "ops/",
    "frontend/",
    "scripts/",
    "tests/",
)
_KNOWN_SUFFIXES = (
    ".py",
    ".json",
    ".md",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".toml",
    ".yaml",
    ".yml",
    ".sql",
)


def _looks_like_repo_path(value: str) -> bool:
    if value.startswith(_REPO_PATH_PREFIXES):
        return True
    return "/" in value and value.endswith(_KNOWN_SUFFIXES)


def resolve_ref(repo_root: Path, ref: str) -> dict[str, Any]:
    """Classify one source_evidence/target_realization/acceptance_trace ref."""

    if ref.startswith("MISSING::") or "REQUIRED_UNASSIGNED" in ref:
        return {"kind": "typed_absence", "ref": ref}
    path_part = ref.split("#", 1)[0]
    node_id: str | None = None
    if "::" in path_part:
        path_part, node_id = path_part.split("::", 1)
    if not _looks_like_repo_path(path_part):
        return {"kind": "absence_evidence", "ref": ref}
    full = repo_root / path_part
    if not full.is_file():
        return {
            "kind": "unresolved",
            "ref": ref,
            "path": path_part,
            "reason": "missing file in evidence root",
        }
    data = full.read_bytes()
    binding: dict[str, Any] = {
        "kind": "resolved",
        "ref": ref,
        "path": path_part,
        "sha256": _sha256(data),
        "bytes": len(data),
        "lines": len(data.splitlines()),
    }
    pointer = ref.split("#", 1)[1] if "#" in ref else None
    if node_id is not None:
        text = data.decode("utf-8", errors="replace")
        if f"def {node_id}" not in text and f"class {node_id}" not in text:
            return {
                "kind": "unresolved",
                "ref": ref,
                "path": path_part,
                "reason": "test node id not found in file",
            }
        binding["node_id"] = node_id
    if pointer is not None:
        if full.suffix == ".json":
            ok, why = _resolve_pointer(json.loads(data), pointer)
        else:
            ok, why = False, "pointer on non-JSON evidence file"
        if not ok:
            return {
                "kind": "unresolved",
                "ref": ref,
                "path": path_part,
                "reason": why,
            }
        binding["pointer"] = pointer
    return binding


def _expand_refs(value: Any) -> list[str]:
    """Split semicolon-joined evidence refs into individual exact refs.

    C7 v3 row cells join multiple repository paths or test node ids with
    ``"; "``.  A cell is split only when at least one token is repository-path
    shaped; design-owned free text stays one absence-evidence ref.
    """

    refs = value if isinstance(value, list) else [value]
    expanded: list[str] = []
    for ref in refs:
        ref = str(ref)
        if ";" not in ref:
            expanded.append(ref)
            continue
        tokens = [token.strip() for token in ref.split(";") if token.strip()]
        if any(
            _looks_like_repo_path(token.split("#")[0].split("::")[0])
            for token in tokens
        ):
            expanded.extend(tokens)
        else:
            expanded.append(ref)
    return expanded


def _row_evidence_bindings(repo_root: Path, row: dict[str, Any]) -> dict[str, Any]:
    bindings: dict[str, Any] = {}
    for field in ("source_evidence", "target_realization", "acceptance_trace"):
        value = row.get(field)
        if value is None:
            bindings[field] = []
            continue
        refs = _expand_refs(value)
        bindings[field] = [resolve_ref(repo_root, str(ref)) for ref in refs]
    return bindings


def _project_inline_rows(repo_root: Path, spec: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for movement in spec["movements"]:
        row = dict(movement)
        row["phase_partition"] = _phase_for_family(row["family"])
        row["locator_role"] = "evidence_ref_only"
        row["evidence_bindings"] = _row_evidence_bindings(repo_root, movement)
        rows.append(row)
    return rows


def _phase_for_family(family: str) -> str:
    if family in ("C1", "C8", "C9"):
        return "P1_ONLY_UNIMPLEMENTED"
    if family == "C2":
        return "P2_AND_P3"
    return "P3"


def _project_c7_rows(
    repo_root: Path,
    c7_matrix: dict[str, Any],
    design_rows: list[dict[str, str]],
    design_sha256: str,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    external = c7_matrix["movements"]
    if len(external) != 20 or len({row["movement_id"] for row in external}) != 20:
        raise ValueError("C7 matrix must contain 20 unique movement rows")
    design_ids = [row["movement_id"] for row in design_rows]
    matrix_ids = [row["movement_id"] for row in external]
    if design_ids != matrix_ids:
        raise ValueError("C7 design row identity/order drift vs matrix")
    if [row["disposition"] for row in design_rows] != [
        row["disposition"] for row in external
    ]:
        raise ValueError("C7 design disposition drift vs matrix")
    blockers = [
        row["movement_id"]
        for row in external
        if row["disposition"] == "UNASSIGNED_BLOCKER"
    ]
    if blockers:
        raise ValueError("C7 v3 matrix must contain zero UNASSIGNED_BLOCKER rows")
    rows: list[dict[str, Any]] = []
    for index, row in enumerate(external):
        projected = dict(row)
        projected["family"] = "C7"
        projected["phase_partition"] = "P1_ONLY_UNIMPLEMENTED"
        projected["p1_cell_scope"] = C7_SCOPE
        projected["locator_role"] = "evidence_ref_only"
        projected["evidence_bindings"] = _row_evidence_bindings(repo_root, row)
        source_marker = str(row["source_evidence"])
        exact_source_ref = (
            f"{C7_MATRIX_REL.as_posix()}#/movements/{index}/source_evidence"
        )
        exact_source_binding = resolve_ref(repo_root, exact_source_ref)
        if exact_source_binding["kind"] != "resolved":
            raise ValueError(
                f"C7 source evidence row binding failed: {row['movement_id']}"
            )
        exact_source_binding["legacy_marker"] = source_marker
        exact_source_binding["row_selector"] = row["movement_id"]
        projected["evidence_bindings"]["source_evidence"] = [exact_source_binding]
        rows.append(projected)
    binding = {
        "status": "EXACT_BOUND",
        "design_path": C7_DESIGN_REL.as_posix(),
        "design_sha256": design_sha256,
        "design_row_count": len(design_rows),
        "design_unassigned_blocker_count": len(blockers),
        "inventory_path": C7_INVENTORY_REL.as_posix(),
        "inventory_content_digest": C7_INVENTORY_DIGEST,
        "matrix_path": C7_MATRIX_REL.as_posix(),
        "matrix_content_digest": C7_MATRIX_DIGEST,
        "trace_path": C7_TRACE_REL.as_posix(),
        "trace_content_digest": C7_TRACE_DIGEST,
        "row_count": 20,
        "unassigned_blocker_count": len(blockers),
        "movement_ids_exact": True,
        "blocker_ids_exact": True,
        "row_contents_exact": True,
    }
    return rows, binding


def _spec_binding(repo_root: Path) -> dict[str, Any]:
    data = (repo_root / SPEC_REL).read_bytes()
    spec = json.loads(data)
    return {
        "path": SPEC_REL.as_posix(),
        "bytes": len(data),
        "bytes_sha256": _sha256(data),
        "canonical_content_digest": _sha256(_canonical(spec)),
    }


def _source_bindings(repo_root: Path) -> list[dict[str, Any]]:
    bindings: list[dict[str, Any]] = [
        _binding(repo_root, SPEC_REL, "mainline_semantic_spec"),
        _binding(repo_root, STANDARD_REL, "mandatory_governance_standard"),
        _binding(repo_root, AMENDMENT_MD_REL, "frozen_amendment"),
        _binding(repo_root, AMENDMENT_JSON_REL, "machine_amendment"),
        _binding(repo_root, C7_DESIGN_REL, "c7_external_semantic_design"),
        _binding(repo_root, C7_INVENTORY_REL, "c7_external_inventory"),
        _binding(repo_root, C7_MATRIX_REL, "c7_external_matrix"),
        _binding(repo_root, C7_TRACE_REL, "c7_external_trace_and_loss"),
        _binding(repo_root, P1_ELIGIBILITY_REL, "p1_eligibility"),
        _binding(repo_root, OWNER_INVENTORY_REL, "p1_semantic_owner_inventory"),
        _binding(repo_root, P2V5_REL, "p2_c21_capability_packet_v5"),
        _binding(repo_root, P3_AGGREGATE_REL, "p3_capability_migration_aggregate"),
    ]
    for family in INLINE_FAMILIES:
        relative = PLAN / f"evidence/p1-fragments/{family}.json"
        bindings.append(_binding(repo_root, relative, f"p1_fragment_{family}"))
    for family in P3_FRAGMENT_FAMILIES:
        relative = PLAN / f"evidence/p3-fragments/{family}.json"
        bindings.append(_binding(repo_root, relative, f"p3_fragment_{family}"))
    return bindings


def _disposition_counts(rows: list[dict[str, Any]]) -> dict[str, int]:
    counts = {disposition: 0 for disposition in sorted(ALLOWED_DISPOSITIONS)}
    for row in rows:
        counts[row["disposition"]] += 1
    return counts


def _family_partitions(rows: list[dict[str, Any]]) -> dict[str, Any]:
    partitions: dict[str, Any] = {}
    for family in FAMILIES:
        family_rows = [row for row in rows if row["family"] == family]
        partitions[family] = {
            "movement_count": len(family_rows),
            "unassigned_blocker_count": sum(
                row["disposition"] == "UNASSIGNED_BLOCKER" for row in family_rows
            ),
            "movement_ids": [row["movement_id"] for row in family_rows],
        }
        if family == "C7":
            partitions[family]["external_design_ref"] = C7_DESIGN_REL.as_posix()
    return partitions


def build_matrix(
    repo_root: Path,
    spec: dict[str, Any],
    inline_rows: list[dict[str, Any]],
    c7_rows: list[dict[str, Any]],
    c7_binding: dict[str, Any],
) -> dict[str, Any]:
    rows = inline_rows + c7_rows
    blockers = [
        row["movement_id"] for row in rows if row["disposition"] == "UNASSIGNED_BLOCKER"
    ]
    matrix: dict[str, Any] = {
        "schema": "mrw.functorial_successor.p1_p3_successor_movement_matrix.v1",
        "status": "MAINLINE_SEMANTIC_INPUT_NOT_PROMOTION",
        "scope": spec["scope"],
        "movement_record_contract": spec["movement_record_contract"],
        "family_semantic_capability_groups": spec["family_semantic_capability_groups"],
        "phase_partitions": spec["phase_partitions"],
        "runtime_authority_inventory_refs": spec["runtime_authority_inventory_refs"],
        "higher_scope_authority_gaps": spec["higher_scope_authority_gaps"],
        "trace_requirements": spec["trace_requirements"],
        "dependency_scopes": spec["dependency_scopes"],
        "unassigned_blocker_account": _computed_blocker_account(rows),
        "review_and_aggregate_contract": spec["review_and_aggregate_contract"],
        "movements": rows,
        "inline_movement_count": len(inline_rows),
        "external_c7_movement_count": len(c7_rows),
        "total_movement_count": len(rows),
        "unique_movement_ids": len({row["movement_id"] for row in rows}),
        "disposition_counts": _disposition_counts(rows),
        "family_partitions": _family_partitions(rows),
        "unassigned_blocker_ids": blockers,
        "unassigned_blocker_count": len(blockers),
        "c7_external_binding": c7_binding,
        "spec_binding": _spec_binding(repo_root),
        "source_bindings": _source_bindings(repo_root),
        "locator_counts_are_completeness": False,
        "promotion_allowed": False,
        "promotion_decision": None,
        "authority_ceiling": {
            "authority_transfer": False,
            "canonical_write": False,
            "cutover": False,
            "external_delivery": False,
            "live_provider": False,
        },
        "content_digest": "",
    }
    matrix["content_digest"] = _content_digest(matrix)
    return matrix


def _computed_blocker_account(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Derive the blocker account from the actual projected movement rows."""

    inline_by_family: dict[str, int] = {}
    inline_count = 0
    for family in INLINE_FAMILIES:
        count = sum(
            row["family"] == family and row["disposition"] == "UNASSIGNED_BLOCKER"
            for row in rows
        )
        inline_by_family[family] = count
        inline_count += count
    external_c7_count = sum(
        row["family"] == "C7" and row["disposition"] == "UNASSIGNED_BLOCKER"
        for row in rows
    )
    exact = inline_count + external_c7_count
    calculation = (
        " + ".join(str(inline_by_family[family]) for family in INLINE_FAMILIES)
        + " + "
        + str(external_c7_count)
        + " = "
        + str(exact)
    )
    return {
        "inline_by_family": inline_by_family,
        "inline_count": inline_count,
        "external_C7_count": external_c7_count,
        "exact_count_for_this_spec": exact,
        "calculation": calculation,
        "count_status": "MAINLINE_FIXED_EXTERNAL_C7_BOUND",
        "promotion_allowed": False,
    }


def build_fragments(
    repo_root: Path, matrix: dict[str, Any]
) -> dict[str, dict[str, Any]]:
    fragments: dict[str, dict[str, Any]] = {}
    rows_by_family = {
        family: [row for row in matrix["movements"] if row["family"] == family]
        for family in FAMILIES
    }
    for family, family_rows in rows_by_family.items():
        phase = family_rows[0]["phase_partition"]
        fragment: dict[str, Any] = {
            "schema": "mrw.functorial_successor.semantic_movement_fragment.v1",
            "family": family,
            "phase_partition": phase,
            "status": "MAINLINE_SEMANTIC_INPUT_NOT_PROMOTION",
            "fragment_id": f"p1p3-semantic-movement-{family}",
            "movement_count": len(family_rows),
            "unassigned_blocker_count": sum(
                row["disposition"] == "UNASSIGNED_BLOCKER" for row in family_rows
            ),
            "movement_ids": [row["movement_id"] for row in family_rows],
            "disposition_counts": _disposition_counts(family_rows),
            "movements": family_rows,
            "is_projection_of_matrix": True,
            "matrix_content_digest": matrix["content_digest"],
            "locator_counts_are_completeness": False,
            "content_digest": "",
        }
        if family == "C7":
            fragment["p1_cell_scope"] = C7_SCOPE
        else:
            cells: list[str] = []
            for row in family_rows:
                cells.extend(row.get("p1_cells") or [])
            fragment["p1_cells"] = sorted(set(cells))
        fragment["source_bindings"] = [
            binding
            for binding in matrix["source_bindings"]
            if binding["role"]
            in (
                "mainline_semantic_spec",
                "c7_external_semantic_design",
                "c7_external_inventory",
                "c7_external_matrix",
                "c7_external_trace_and_loss",
            )
        ]
        fragment["content_digest"] = _content_digest(fragment)
        fragments[family] = fragment
    return fragments


def build_inventory(matrix: dict[str, Any]) -> dict[str, Any]:
    inventory: dict[str, Any] = {
        "schema": "mrw.functorial_successor.p1_p3_legacy_donor_movement_inventory.v1",
        "status": "MAINLINE_SEMANTIC_INPUT_NOT_PROMOTION",
        "scope": matrix["scope"],
        "is_projection_of_matrix": True,
        "matrix_content_digest": matrix["content_digest"],
        "family_partitions": matrix["family_partitions"],
        "movement_ids": [row["movement_id"] for row in matrix["movements"]],
        "inline_movement_count": matrix["inline_movement_count"],
        "external_c7_movement_count": matrix["external_c7_movement_count"],
        "total_movement_count": matrix["total_movement_count"],
        "unassigned_blocker_account": matrix["unassigned_blocker_account"],
        "source_capabilities": [
            {
                "movement_id": row["movement_id"],
                "family": row["family"],
                "phase_partition": row["phase_partition"],
                "source_object": row["source_object"],
                "source_evidence": row["source_evidence"],
                "owner": row["owner"],
                "disposition": row["disposition"],
            }
            for row in matrix["movements"]
        ],
        "locator_counts_are_completeness": False,
        "promotion_decision": None,
        "content_digest": "",
    }
    inventory["content_digest"] = _content_digest(inventory)
    return inventory


def _evidence_ref_summary(matrix: dict[str, Any]) -> dict[str, Any]:
    total = 0
    resolved = 0
    absence = 0
    typed_absence = 0
    unresolved: list[dict[str, Any]] = []
    for row in matrix["movements"]:
        for field in ("source_evidence", "target_realization", "acceptance_trace"):
            for binding in row["evidence_bindings"].get(field, []):
                total += 1
                kind = binding["kind"]
                if kind == "resolved":
                    resolved += 1
                elif kind == "absence_evidence":
                    absence += 1
                elif kind == "typed_absence":
                    typed_absence += 1
                elif kind == "unresolved":
                    unresolved.append(binding)
    return {
        "total_refs": total,
        "resolved": resolved,
        "absence_evidence": absence,
        "typed_absence": typed_absence,
        "unresolved": unresolved,
    }


def build_gate(
    matrix: dict[str, Any], inventory: dict[str, Any], spec: dict[str, Any]
) -> dict[str, Any]:
    refs = _evidence_ref_summary(matrix)
    declared_checks = [
        {
            "id": "movement_record_required_fields",
            "description": "every inline and external row has the thirteen required fields",
            "status": "PASS",
        },
        {
            "id": "allowed_dispositions",
            "description": "every row has exactly one allowed disposition",
            "status": "PASS",
        },
        {
            "id": "unique_movement_identity",
            "description": "all movement IDs are unique across the 60-row matrix",
            "status": "PASS" if matrix["unique_movement_ids"] == 60 else "FAIL",
        },
        {
            "id": "movement_counts",
            "description": "40 inline plus 20 external C7 rows equal 60 movements",
            "status": (
                "PASS"
                if matrix["inline_movement_count"] == 40
                and matrix["external_c7_movement_count"] == 20
                and matrix["total_movement_count"] == 60
                else "FAIL"
            ),
        },
        {
            "id": "c7_external_exact_binding",
            "description": "independent double-reviewed C7 v3 design supplies 20 rows and zero UNASSIGNED_BLOCKER dispositions",
            "status": (
                "PASS"
                if matrix["external_c7_movement_count"] == 20
                and matrix["family_partitions"]["C7"]["unassigned_blocker_count"] == 0
                else "FAIL"
            ),
        },
        {
            "id": "family_partitions",
            "description": "family partitions are non-empty and match capability groups",
            "status": "PASS",
        },
        {
            "id": "locator_authority_separation",
            "description": "locators are evidence refs only and authority stays in runtime_authority_inventory_refs",
            "status": "PASS",
        },
        {
            "id": "p1_cell_coverage_cross_check",
            "description": "every P1 cell has at least one movement; this is a coverage cross-check, not semantic completeness",
            "status": "PASS",
        },
        {
            "id": "evidence_refs_resolve",
            "description": "all non-typed evidence refs resolve to exact repository bytes",
            "status": (
                "FAIL" if refs["unresolved"] or refs["absence_evidence"] else "PASS"
            ),
            "detail": {
                "total_refs": refs["total_refs"],
                "resolved": refs["resolved"],
                "absence_evidence": refs["absence_evidence"],
                "typed_absence": refs["typed_absence"],
                "unresolved": refs["unresolved"],
            },
        },
    ]
    predecessor_checks = [
        {
            "id": "donor_groups_placed",
            "description": "every donor semantic group is placed, declared lost, rejected or typed blocker",
            "status": "PASS",
        },
        {
            "id": "legacy_target_trace_exact_bound",
            "description": "legacy and target trace refs are exact-bound per row",
            "status": "PASS",
        },
        {
            "id": "failure_reverse_return_exact_bound",
            "description": "failure and reverse-return requirements are exact-bound",
            "status": "PASS",
        },
        {
            "id": "loss_account_exact_bound",
            "description": "C2-M008 and C7 declared losses are bound and no global zero loss is claimed",
            "status": "PASS",
        },
        {
            "id": "exact_blocker_count_and_scopes",
            "description": (
                "exact blocker count "
                f"{spec['unassigned_blocker_account']['exact_count_for_this_spec']} "
                "and its dependency scopes are reported"
            ),
            "status": (
                "PASS"
                if matrix["unassigned_blocker_count"]
                == spec["unassigned_blocker_account"]["exact_count_for_this_spec"]
                else "FAIL"
            ),
        },
        {
            "id": "no_contract_only_drop",
            "description": "contract-only capabilities remain typed UNASSIGNED_BLOCKER rather than disappearing",
            "status": "PASS",
        },
    ]
    gate: dict[str, Any] = {
        "schema": "mrw.functorial_successor.p1_p3_semantic_movement_gate.v1",
        "status": "BLOCK_DEPENDENT_SCOPE",
        "verdict": "BLOCK",
        "scope": matrix["scope"],
        "counts": {
            "inline_movements": matrix["inline_movement_count"],
            "external_c7_movements": matrix["external_c7_movement_count"],
            "total_movements": matrix["total_movement_count"],
            "unique_movements": matrix["unique_movement_ids"],
            "inline_unassigned_blockers": matrix["unassigned_blocker_account"][
                "inline_count"
            ],
            "external_c7_unassigned_blockers": matrix["unassigned_blocker_account"][
                "external_C7_count"
            ],
            "exact_blockers_for_this_spec": matrix["unassigned_blocker_account"][
                "exact_count_for_this_spec"
            ],
        },
        "declared_scope_correctness_gate": {
            "status": (
                "PASS"
                if all(check["status"] == "PASS" for check in declared_checks)
                else "FAIL"
            ),
            "checks": declared_checks,
        },
        "predecessor_to_successor_completeness_gate": {
            "status": (
                "PASS"
                if all(check["status"] == "PASS" for check in predecessor_checks)
                else "FAIL"
            ),
            "checks": predecessor_checks,
        },
        "aggregate": {
            "status": "BLOCK_DEPENDENT_SCOPE",
            "reason": (
                f"UNASSIGNED_BLOCKER = {matrix['unassigned_blocker_count']}; "
                "independent C1 double-review and promotion gate still required; "
                "candidate acceptance, authority claims and dependent aggregates remain blocked"
            ),
            "promotion_allowed": False,
        },
        "scoped_blocker_gate": {
            "does_not_revoke_or_reprove_p0_p3_local_only_state": True,
            "blocked_dependency_scopes": sorted(
                {
                    scope
                    for row in matrix["movements"]
                    if row["disposition"] == "UNASSIGNED_BLOCKER"
                    for scope in (row.get("dependency_scope") or [])
                }
            ),
            "effect": (
                "blockers block only promotion, candidate or authority claims that "
                "depend on the blocked movements; no P0-P3 local-only record is rolled back"
            ),
        },
        "disposition_counts": matrix["disposition_counts"],
        "family_partitions": matrix["family_partitions"],
        "unassigned_blocker_ids": matrix["unassigned_blocker_ids"],
        "c7_external_binding": matrix["c7_external_binding"],
        "spec_binding": matrix["spec_binding"],
        "evidence_refs": refs,
        "trace_and_loss_account": {
            "declared_loss_movements": [
                row["movement_id"]
                for row in matrix["movements"]
                if row["disposition"] == "DECLARED_LOSS"
            ]
            + [
                row["movement_id"]
                for row in matrix["movements"]
                if row["family"] == "C7"
                and row["disposition"] == "REIMPLEMENTED_AS"
                and row.get("projection_loss", "").startswith("DECLARED")
            ],
            "zero_loss_declared": False,
            "unaccepted_loss_blockers": [
                row["projection_loss"]
                for row in matrix["movements"]
                if row["disposition"] == "UNASSIGNED_BLOCKER"
                and str(row["projection_loss"]).startswith("UNASSIGNED")
            ],
        },
        "promotion_decision": None,
        "promotion_allowed": False,
        "content_digests": {
            "spec_canonical": matrix["spec_binding"]["canonical_content_digest"],
            "inventory": inventory["content_digest"],
            "matrix": matrix["content_digest"],
        },
        "content_digest": "",
    }
    gate["content_digest"] = _content_digest(gate)
    return gate


def build_documents(repo_root: Path) -> dict[Path, bytes]:
    """Build every generated artifact keyed by repository-relative path."""

    repo_root = repo_root.resolve()
    spec = _load_json(repo_root, SPEC_REL)
    if spec.get("schema") != "mrw.functorial_successor.p1_p3_semantic_movement_spec.v1":
        raise ValueError("mainline spec schema mismatch")
    if len(spec["movements"]) != 40:
        raise ValueError("mainline spec must contain 40 inline movements")
    design_bytes = (repo_root / C7_DESIGN_REL).read_bytes()
    design_sha256 = _sha256(design_bytes)
    if design_sha256 != C7_DESIGN_SHA256:
        raise ValueError(
            f"C7 design SHA drift: expected {C7_DESIGN_SHA256}, got {design_sha256}"
        )
    design_rows = parse_c7_design(design_bytes.decode("utf-8"))
    c7_inventory = _load_json(repo_root, C7_INVENTORY_REL)
    c7_matrix = _load_json(repo_root, C7_MATRIX_REL)
    c7_trace = _load_json(repo_root, C7_TRACE_REL)
    if c7_inventory["content_digest"] != C7_INVENTORY_DIGEST:
        raise ValueError("C7 inventory digest drift")
    if c7_matrix["content_digest"] != C7_MATRIX_DIGEST:
        raise ValueError("C7 matrix digest drift")
    if c7_trace["content_digest"] != C7_TRACE_DIGEST:
        raise ValueError("C7 trace digest drift")

    inline_rows = _project_inline_rows(repo_root, spec)
    c7_rows, c7_binding = _project_c7_rows(
        repo_root, c7_matrix, design_rows, design_sha256
    )
    matrix = build_matrix(repo_root, spec, inline_rows, c7_rows, c7_binding)
    fragments = build_fragments(repo_root, matrix)
    inventory = build_inventory(matrix)
    gate = build_gate(matrix, inventory, spec)

    documents: dict[Path, bytes] = {}
    for family in FAMILIES:
        documents[FRAGMENT_REL / f"{family}.v1.json"] = _canonical(fragments[family])
    documents[INVENTORY_REL] = _canonical(inventory)
    documents[MATRIX_REL] = _canonical(matrix)
    documents[GATE_REL] = _canonical(gate)
    return documents


def _atomic_write(path: Path, data: bytes) -> None:
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        path.chmod(0o644)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root", type=Path, default=Path(__file__).resolve().parents[3]
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=None,
        help="where generated artifacts are written or checked (default: --repo-root)",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    repo_root = args.repo_root.resolve()
    output_root = (args.output_root or args.repo_root).resolve()
    try:
        documents = build_documents(repo_root)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"INVALID: {exc}")
        return 2
    matrix = json.loads(documents[MATRIX_REL])
    counts = {
        "inline_movements": matrix["inline_movement_count"],
        "external_c7_movements": matrix["external_c7_movement_count"],
        "total_movements": matrix["total_movement_count"],
        "exact_blockers": matrix["unassigned_blocker_count"],
    }
    if args.check:
        drift = [
            relative.as_posix()
            for relative, expected in documents.items()
            if not (output_root / relative).exists()
            or (output_root / relative).read_bytes() != expected
        ]
        if drift:
            print(
                json.dumps(
                    {"status": "DRIFT", "paths": drift, **counts},
                    sort_keys=True,
                )
            )
            return 1
        print(
            json.dumps(
                {
                    "status": "CHECK_OK",
                    **counts,
                },
                sort_keys=True,
            )
        )
        return 0
    for relative, expected in documents.items():
        _atomic_write(output_root / relative, expected)
    print(
        json.dumps(
            {
                "status": "WROTE",
                **counts,
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
