from __future__ import annotations

LOTTERY_TOKENS = {
    "lottery",
    "lotto",
    "jackpot",
    "ticket",
    "tickets",
    "numbers",
    "powerball",
    "megamillions",
    "mega millions",
    "scratch",
    "scratcher",
    "scratchers",
    "raffle",
    "syndicate",
    "pick",
    "keno",
    "cash 5",
    "cash5",
    "cash4life",
    "cash 4 life",
    "lottery pool",
    "group lottery",
    "lottery syndicate",
    "jackpot drawing",
    "number drawing",
}
