"""Clue Chain service helpers."""

from .contracts import (
    CANDIDATE_STATUSES,
    CHAIN_STATUSES,
    DECISIONS,
    EDGE_STATUSES,
    EVIDENCE_STATUSES,
    HOP_STATUSES,
    STATE_CONTRACT_VERSION,
    Chain,
    ChainCandidate,
    ChainDecision,
    ChainEdge,
    ChainEvidence,
    ChainHop,
)
from .external_search_expansion import (
    CONTRACT_VERSION as CLUE_CHAIN_EXTERNAL_SEARCH_EXPANSION_CONTRACT_VERSION,
    ExternalSearchExpansionRequest,
    FixtureExternalSearchProvider,
    LiveHookExternalSearchProvider,
    build_external_search_provider,
    expand_external_search,
    external_search_dedupe_key,
    normalize_external_search_url,
)
from .graph_integration import (
    CLUE_CHAIN_GRAPH_MUTATION_CONTRACT_VERSION,
    CLUE_CHAIN_GRAPH_SUBMIT_BRIDGE_CONTRACT_VERSION,
    ClueChainGraphIntegrationError,
    build_graph_evidence_pack,
    build_graph_handoff_payload,
    build_graph_mutation_payload,
    build_graph_submit_bridge_envelope,
)
from .source_library_expansion import (
    CLUE_CHAIN_SOURCE_LIBRARY_EXPANSION_CONTRACT_VERSION,
    expand_source_library_hop,
    merge_candidate_aliases,
)
from .service import (
    ClueChainClosedError,
    ClueChainNotFoundError,
    ClueChainObjectMissingError,
    ClueChainService,
    merge_alias_values,
    normalize_alias,
    stable_id,
)
from .store import InMemoryClueChainStore, IngestConfigClueChainStore, build_clue_chain_store

__all__ = [
    "CANDIDATE_STATUSES",
    "CHAIN_STATUSES",
    "CLUE_CHAIN_EXTERNAL_SEARCH_EXPANSION_CONTRACT_VERSION",
    "CLUE_CHAIN_GRAPH_MUTATION_CONTRACT_VERSION",
    "CLUE_CHAIN_GRAPH_SUBMIT_BRIDGE_CONTRACT_VERSION",
    "CLUE_CHAIN_SOURCE_LIBRARY_EXPANSION_CONTRACT_VERSION",
    "DECISIONS",
    "EDGE_STATUSES",
    "EVIDENCE_STATUSES",
    "HOP_STATUSES",
    "STATE_CONTRACT_VERSION",
    "Chain",
    "ChainCandidate",
    "ChainDecision",
    "ChainEdge",
    "ChainEvidence",
    "ChainHop",
    "ClueChainClosedError",
    "ClueChainGraphIntegrationError",
    "ClueChainNotFoundError",
    "ClueChainObjectMissingError",
    "ClueChainService",
    "ExternalSearchExpansionRequest",
    "FixtureExternalSearchProvider",
    "InMemoryClueChainStore",
    "IngestConfigClueChainStore",
    "LiveHookExternalSearchProvider",
    "build_clue_chain_store",
    "build_external_search_provider",
    "build_graph_evidence_pack",
    "build_graph_handoff_payload",
    "build_graph_mutation_payload",
    "build_graph_submit_bridge_envelope",
    "expand_external_search",
    "expand_source_library_hop",
    "external_search_dedupe_key",
    "merge_alias_values",
    "merge_candidate_aliases",
    "normalize_alias",
    "normalize_external_search_url",
    "stable_id",
]
