FROM mrw-local/r13x-candidate-backend:8c965dd2dcdc5d3e0883c3d7f65fb720dc2d87a2
COPY main/backend/docker-entrypoint.sh /docker-entrypoint.sh
COPY main/backend/app/composition/production.py /app/app/composition/production.py
RUN chmod 0555 /docker-entrypoint.sh
