"""I1 successor family assembly package."""

from app.successor_runtime.substrate.projections.registry import ProjectorRegistry

from .base import (
    ASSEMBLY_STATUSES,
    PROJECTOR_REGISTRY_INCARNATION,
    AssemblyStatus,
    C3AssemblyOptions,
    C4AssemblyOptions,
    C5AssemblyOptions,
    C6AssemblyOptions,
    C7AssemblyOptions,
    C8AssemblyOptions,
    C9AssemblyOptions,
    CellBinding,
    FamilyAssembly,
    FamilyAssemblyOptions,
    KernelWiring,
    ProjectorSourceKey,
    ProjectorWiring,
    RollbackBindingDeclaration,
    local_assembly_scope_digest,
    merge_family_assemblies,
    require_assembly_digest,
    sha256_hex,
    successor_binding,
)
from .successor_assembly import (
    ALL_I1_CELLS,
    SuccessorAssembly,
    assemble_successor_runtime,
    build_local_offline_fixture_options,
)

__all__ = [
    "ALL_I1_CELLS",
    "ASSEMBLY_STATUSES",
    "PROJECTOR_REGISTRY_INCARNATION",
    "AssemblyStatus",
    "C3AssemblyOptions",
    "C4AssemblyOptions",
    "C5AssemblyOptions",
    "C6AssemblyOptions",
    "C7AssemblyOptions",
    "C8AssemblyOptions",
    "C9AssemblyOptions",
    "CellBinding",
    "FamilyAssembly",
    "FamilyAssemblyOptions",
    "KernelWiring",
    "ProjectorRegistry",
    "ProjectorSourceKey",
    "ProjectorWiring",
    "RollbackBindingDeclaration",
    "SuccessorAssembly",
    "assemble_successor_runtime",
    "build_local_offline_fixture_options",
    "local_assembly_scope_digest",
    "merge_family_assemblies",
    "require_assembly_digest",
    "sha256_hex",
    "successor_binding",
]
