"""Capability-owned operation contracts for the MRW functorial successor."""

from .catalog import CapabilityCatalogSnapshot, build_first_specimen_catalog
from .contracts import (
    ObjectType,
    OperationContract,
    OperationContractCatalogSnapshot,
    OperationContractRef,
    OperationSpec,
)
from .first_specimen import (
    CanonicalReadInput,
    CaptureDocumentSnapshotInput,
    ClaimOrGapInput,
    EvidenceQualificationInput,
    FirstSpecimenCapabilityBundle,
    InternalExportInput,
    MarkdownComposeInput,
    build_first_specimen_bundle,
)
from .first_specimen_payloads import (
    FirstSpecimenPayloadContext,
    PersistedOperationPayloads,
    SourcePayloadContext,
    persist_first_specimen_payloads,
    persist_internal_export_payload,
)
from .first_specimen_delivery_gate import (
    DeliveryApprovalSnapshot,
    DeliveryAssignmentParameters,
    DeliveryAssignmentRequest,
    DeliveryAuthoritySnapshot,
    DeliveryGate,
    DeliveryGateCommand,
    DeliveryGateReceipt,
    DeliveryGateRejected,
    DeliveryIntentTemplate,
    DeliveryReadyPacket,
)
from .first_specimen_interpreters import FirstSpecimenInterpreters, derive_material_ref
from .first_specimen_program import (
    DELIVERY_TEMPLATE_TYPE,
    ExactOperationValues,
    FirstSpecimenProgramValues,
    build_runtime_first_specimen_program,
)
from .first_specimen_submission import (
    CaptureReceipt,
    CompileAssignmentRequest,
    FirstSpecimenSubmissionService,
    SubmissionCommand,
    SubmissionRejected,
    SubmittedFirstSpecimen,
    SubmittedRuntimePacket,
)
from .fixture import FIXTURE_OPERATION_KIND, build_fixture_capability_bundle

from .acquisition_batch_interpreters import (
    COLLECT_EXECUTE_BATCH_ELEMENT_LEGACY_INTERPRETER_ID,
    COLLECT_FOLD_ORDERED_RESULTS_LEGACY_INTERPRETER_ID,
    CollectBindingMismatch,
    InterpreterFailure,
    InterpreterSuccess,
    authority_requirement_digest,
    deterministic_composed_element_runner,
    legacy_execute_element_interpreter_profile_digest,
    legacy_fold_ordered_results_interpreter_profile_digest,
    require_exact_collect_binding,
    require_exact_composed_binding,
    run_ordered_traversal,
    successor_execute_element_interpreter_profile_digest,
    successor_fold_ordered_results_interpreter_profile_digest,
)
from .knowledge_graph_projection_contribution import (
    KNOWLEDGE_GRAPH_PROJECTION_DECLARED_LOSS as KNOWLEDGE_GRAPH_PROJECTION_DECLARED_LOSS,
    KNOWLEDGE_GRAPH_PROJECTION_INPUT_TYPE as KNOWLEDGE_GRAPH_PROJECTION_INPUT_TYPE,
    KNOWLEDGE_GRAPH_PROJECTION_KIND as KNOWLEDGE_GRAPH_PROJECTION_KIND,
    KNOWLEDGE_GRAPH_PROJECTION_OPERATION_ID as KNOWLEDGE_GRAPH_PROJECTION_OPERATION_ID,
    KNOWLEDGE_GRAPH_PROJECTION_OWNER as KNOWLEDGE_GRAPH_PROJECTION_OWNER,
    KNOWLEDGE_GRAPH_PROJECTION_PAYLOAD_CODEC_ID as KNOWLEDGE_GRAPH_PROJECTION_PAYLOAD_CODEC_ID,
    KNOWLEDGE_GRAPH_PROJECTION_RESULT_TYPE as KNOWLEDGE_GRAPH_PROJECTION_RESULT_TYPE,
    KNOWLEDGE_GRAPH_PROJECTION_RETURN_CONTRACT_REF as KNOWLEDGE_GRAPH_PROJECTION_RETURN_CONTRACT_REF,
    KNOWLEDGE_GRAPH_PROJECTION_ROLLBACK_REF as KNOWLEDGE_GRAPH_PROJECTION_ROLLBACK_REF,
    KnowledgeCellDefinition as KnowledgeCellDefinition,
    KnowledgeGraphProjectInput as KnowledgeGraphProjectInput,
    KnowledgeGraphProjectionAssemblyContext as KnowledgeGraphProjectionAssemblyContext,
    KnowledgeGraphProjectionRuntimeBinding as KnowledgeGraphProjectionRuntimeBinding,
    knowledge_graph_projection_definition_issues as knowledge_graph_projection_definition_issues,
)
from .knowledge_native_contribution import (
    KnowledgeNativeAssemblyContext as KnowledgeNativeAssemblyContext,
    KnowledgeNativeAssemblyDeclaration as KnowledgeNativeAssemblyDeclaration,
    KnowledgeNativeAuthorSource as KnowledgeNativeAuthorSource,
    KnowledgeNativeDefinition as KnowledgeNativeDefinition,
    KnowledgeNativeOperationSource as KnowledgeNativeOperationSource,
    KnowledgeNativeRuntimeBinding as KnowledgeNativeRuntimeBinding,
    KNOWLEDGE_NATIVE_CONTRIBUTION_RULE as KNOWLEDGE_NATIVE_CONTRIBUTION_RULE,
)
from .typed_knowledge_contribution import (
    KNOWLEDGE_READ_INPUT_TYPE as KNOWLEDGE_READ_INPUT_TYPE,
    KNOWLEDGE_READ_KIND as KNOWLEDGE_READ_KIND,
    KNOWLEDGE_READ_OPERATION_ID as KNOWLEDGE_READ_OPERATION_ID,
    KNOWLEDGE_READ_OWNER as KNOWLEDGE_READ_OWNER,
    KNOWLEDGE_READ_PAYLOAD_CODEC_ID as KNOWLEDGE_READ_PAYLOAD_CODEC_ID,
    KNOWLEDGE_READ_RESULT_TYPE as KNOWLEDGE_READ_RESULT_TYPE,
    KNOWLEDGE_READ_ROLLBACK_REFS as KNOWLEDGE_READ_ROLLBACK_REFS,
    KnowledgeDemandReadInput as KnowledgeDemandReadInput,
    KNOWLEDGE_TYPED_KNOWLEDGE_NATIVE as KNOWLEDGE_TYPED_KNOWLEDGE_NATIVE,
)
from .knowledge_writing_contribution import (
    KNOWLEDGE_WRITING_COMPOSE_INPUT_TYPE as KNOWLEDGE_WRITING_COMPOSE_INPUT_TYPE,
    KNOWLEDGE_WRITING_COMPOSE_KIND as KNOWLEDGE_WRITING_COMPOSE_KIND,
    KNOWLEDGE_WRITING_COMPOSE_OPERATION_ID as KNOWLEDGE_WRITING_COMPOSE_OPERATION_ID,
    KNOWLEDGE_WRITING_COMPOSE_PAYLOAD_CODEC_ID as KNOWLEDGE_WRITING_COMPOSE_PAYLOAD_CODEC_ID,
    KNOWLEDGE_WRITING_COMPOSE_RESULT_TYPE as KNOWLEDGE_WRITING_COMPOSE_RESULT_TYPE,
    KNOWLEDGE_WRITING_OWNER as KNOWLEDGE_WRITING_OWNER,
    KNOWLEDGE_WRITING_ROLLBACK_REFS as KNOWLEDGE_WRITING_ROLLBACK_REFS,
    KNOWLEDGE_WRITING_STAGE_INPUT_TYPE as KNOWLEDGE_WRITING_STAGE_INPUT_TYPE,
    KNOWLEDGE_WRITING_STAGE_KIND as KNOWLEDGE_WRITING_STAGE_KIND,
    KNOWLEDGE_WRITING_STAGE_OPERATION_ID as KNOWLEDGE_WRITING_STAGE_OPERATION_ID,
    KNOWLEDGE_WRITING_STAGE_RESULT_TYPE as KNOWLEDGE_WRITING_STAGE_RESULT_TYPE,
    KnowledgeWritingComposeInput as KnowledgeWritingComposeInput,
    knowledge_writing_native_contribution as knowledge_writing_native_contribution,
)
from .knowledge_report_contribution import (
    KNOWLEDGE_REPORT_INPUT_TYPE as KNOWLEDGE_REPORT_INPUT_TYPE,
    KNOWLEDGE_REPORT_KIND as KNOWLEDGE_REPORT_KIND,
    KNOWLEDGE_REPORT_OPERATION_ID as KNOWLEDGE_REPORT_OPERATION_ID,
    KNOWLEDGE_REPORT_OWNER as KNOWLEDGE_REPORT_OWNER,
    KNOWLEDGE_REPORT_PAYLOAD_CODEC_ID as KNOWLEDGE_REPORT_PAYLOAD_CODEC_ID,
    KNOWLEDGE_REPORT_RESULT_TYPE as KNOWLEDGE_REPORT_RESULT_TYPE,
    KNOWLEDGE_REPORT_ROLLBACK_REF as KNOWLEDGE_REPORT_ROLLBACK_REF,
    KnowledgeReportStageInput as KnowledgeReportStageInput,
    knowledge_report_native_contribution as knowledge_report_native_contribution,
)
from .retrieval_candidate_native import (
    DEFAULT_CANDIDATE_NATIVE_SOURCE,
    compile_candidate_native_contribution,
)
from .retrieval_flow_native import (
    DEFAULT_RETRIEVAL_FLOW_SOURCE,
    compile_retrieval_flow_native,
)
from .retrieval_semantics_native import (
    DEFAULT_RETRIEVAL_SEMANTICS_SOURCE,
    compile_retrieval_semantics_native,
)


__all__ = [
    "COLLECT_EXECUTE_BATCH_ELEMENT_LEGACY_INTERPRETER_ID",
    "COLLECT_FOLD_ORDERED_RESULTS_LEGACY_INTERPRETER_ID",
    "CollectBindingMismatch",
    "InterpreterFailure",
    "InterpreterSuccess",
    "authority_requirement_digest",
    "deterministic_composed_element_runner",
    "legacy_execute_element_interpreter_profile_digest",
    "legacy_fold_ordered_results_interpreter_profile_digest",
    "require_exact_collect_binding",
    "require_exact_composed_binding",
    "run_ordered_traversal",
    "successor_execute_element_interpreter_profile_digest",
    "successor_fold_ordered_results_interpreter_profile_digest",
    "KNOWLEDGE_GRAPH_PROJECTION_DECLARED_LOSS",
    "KNOWLEDGE_GRAPH_PROJECTION_INPUT_TYPE",
    "KNOWLEDGE_GRAPH_PROJECTION_KIND",
    "KNOWLEDGE_GRAPH_PROJECTION_OPERATION_ID",
    "KNOWLEDGE_GRAPH_PROJECTION_OWNER",
    "KNOWLEDGE_GRAPH_PROJECTION_PAYLOAD_CODEC_ID",
    "KNOWLEDGE_GRAPH_PROJECTION_RESULT_TYPE",
    "KNOWLEDGE_GRAPH_PROJECTION_RETURN_CONTRACT_REF",
    "KNOWLEDGE_GRAPH_PROJECTION_ROLLBACK_REF",
    "KnowledgeCellDefinition",
    "KnowledgeGraphProjectInput",
    "KnowledgeGraphProjectionAssemblyContext",
    "KnowledgeGraphProjectionRuntimeBinding",
    "knowledge_graph_projection_definition_issues",
    "KnowledgeNativeAssemblyContext",
    "KnowledgeNativeAssemblyDeclaration",
    "KnowledgeNativeAuthorSource",
    "KnowledgeNativeDefinition",
    "KnowledgeNativeOperationSource",
    "KnowledgeNativeRuntimeBinding",
    "KNOWLEDGE_READ_INPUT_TYPE",
    "KNOWLEDGE_READ_KIND",
    "KNOWLEDGE_READ_OPERATION_ID",
    "KNOWLEDGE_READ_OWNER",
    "KNOWLEDGE_READ_PAYLOAD_CODEC_ID",
    "KNOWLEDGE_READ_RESULT_TYPE",
    "KNOWLEDGE_READ_ROLLBACK_REFS",
    "KNOWLEDGE_WRITING_COMPOSE_INPUT_TYPE",
    "KNOWLEDGE_WRITING_COMPOSE_KIND",
    "KNOWLEDGE_WRITING_COMPOSE_OPERATION_ID",
    "KNOWLEDGE_WRITING_COMPOSE_PAYLOAD_CODEC_ID",
    "KNOWLEDGE_WRITING_COMPOSE_RESULT_TYPE",
    "KNOWLEDGE_WRITING_OWNER",
    "KNOWLEDGE_WRITING_ROLLBACK_REFS",
    "KNOWLEDGE_WRITING_STAGE_INPUT_TYPE",
    "KNOWLEDGE_WRITING_STAGE_KIND",
    "KNOWLEDGE_WRITING_STAGE_OPERATION_ID",
    "KNOWLEDGE_WRITING_STAGE_RESULT_TYPE",
    "KnowledgeWritingComposeInput",
    "knowledge_writing_native_contribution",
    "KNOWLEDGE_REPORT_INPUT_TYPE",
    "KNOWLEDGE_REPORT_KIND",
    "KNOWLEDGE_REPORT_OPERATION_ID",
    "KNOWLEDGE_REPORT_OWNER",
    "KNOWLEDGE_REPORT_PAYLOAD_CODEC_ID",
    "KNOWLEDGE_REPORT_RESULT_TYPE",
    "KNOWLEDGE_REPORT_ROLLBACK_REF",
    "KnowledgeDemandReadInput",
    "KnowledgeReportStageInput",
    "KNOWLEDGE_TYPED_KNOWLEDGE_NATIVE",
    "knowledge_report_native_contribution",
    "DEFAULT_CANDIDATE_NATIVE_SOURCE",
    "DEFAULT_RETRIEVAL_FLOW_SOURCE",
    "DEFAULT_RETRIEVAL_SEMANTICS_SOURCE",
    "compile_candidate_native_contribution",
    "compile_retrieval_flow_native",
    "compile_retrieval_semantics_native",
    "DELIVERY_TEMPLATE_TYPE",
    "FIXTURE_OPERATION_KIND",
    "CanonicalReadInput",
    "CapabilityCatalogSnapshot",
    "CaptureDocumentSnapshotInput",
    "CaptureReceipt",
    "ClaimOrGapInput",
    "CompileAssignmentRequest",
    "DeliveryApprovalSnapshot",
    "DeliveryAssignmentParameters",
    "DeliveryAssignmentRequest",
    "DeliveryAuthoritySnapshot",
    "DeliveryGate",
    "DeliveryGateCommand",
    "DeliveryGateReceipt",
    "DeliveryGateRejected",
    "DeliveryIntentTemplate",
    "DeliveryReadyPacket",
    "EvidenceQualificationInput",
    "ExactOperationValues",
    "FirstSpecimenCapabilityBundle",
    "FirstSpecimenInterpreters",
    "InternalExportInput",
    "FirstSpecimenPayloadContext",
    "FirstSpecimenProgramValues",
    "FirstSpecimenSubmissionService",
    "MarkdownComposeInput",
    "ObjectType",
    "OperationContract",
    "OperationContractCatalogSnapshot",
    "OperationContractRef",
    "OperationSpec",
    "PersistedOperationPayloads",
    "SourcePayloadContext",
    "SubmissionCommand",
    "SubmissionRejected",
    "SubmittedFirstSpecimen",
    "SubmittedRuntimePacket",
    "build_first_specimen_bundle",
    "build_first_specimen_catalog",
    "build_fixture_capability_bundle",
    "build_runtime_first_specimen_program",
    "derive_material_ref",
    "persist_first_specimen_payloads",
    "persist_internal_export_payload",
]
