"""Shared workflow identities and typed failures for compile and observation."""

from __future__ import annotations

from typing import Literal, get_args

from functorial_kit import define_failure_family

WORKFLOW_DSL_INPUT_VERSION = "1.0"
WORKFLOW_DSL_RECEIPT_SCHEMA = "mrw.workflow.definition.compile.receipt.v2"
HISTORICAL_C1_DSL_RECEIPT_SCHEMA = (
    "mrw.functorial-successor.c1.legacy-dsl-receipt.v1"
)
WORKFLOW_DSL_PROGRAM_SCHEMA = "mrw.workflow.definition.compile.program.v2"
WORKFLOW_DSL_PROJECT_SCOPE_SCHEMA = "mrw.workflow.definition.compile.project-scope.v2"
WORKFLOW_DSL_PROGRAM_METADATA_SCHEMA = (
    "mrw.workflow.definition.compile.program-metadata.v2"
)

WORKFLOW_ACCEPTANCE_SCHEMA = "mrw.workflow.runtime.acceptance.v2"
HISTORICAL_C1_ACCEPTANCE_SCHEMA = (
    "mrw.functorial-successor.c1-slice-acceptance.v1"
)

WORKFLOW_DSL_MALFORMED_PAYLOAD = "WORKFLOW_DSL_MALFORMED_PAYLOAD"
WORKFLOW_DSL_DUPLICATE_NODE_ID = "WORKFLOW_DSL_DUPLICATE_NODE_ID"
WORKFLOW_DSL_UNSUPPORTED_NODE_TYPE = "WORKFLOW_DSL_UNSUPPORTED_NODE_TYPE"
WORKFLOW_DSL_MISSING_ENDPOINT = "WORKFLOW_DSL_MISSING_ENDPOINT"
WORKFLOW_DSL_CYCLE = "WORKFLOW_DSL_CYCLE"
WORKFLOW_DSL_COMPILE_FAILURE = "WORKFLOW_DSL_COMPILE_FAILURE"
WORKFLOW_CONTRACT_KIND_UNSUPPORTED = "WORKFLOW_CONTRACT_KIND_UNSUPPORTED"
WORKFLOW_RECEIPT_CONTRACT_INVALID = "WORKFLOW_RECEIPT_CONTRACT_INVALID"
WORKFLOW_ACCEPTANCE_DIGEST_INVALID = "WORKFLOW_ACCEPTANCE_DIGEST_INVALID"
WORKFLOW_ACCEPTANCE_INPUT_INVALID = "WORKFLOW_ACCEPTANCE_INPUT_INVALID"
WORKFLOW_OBSERVATION_SHAPE_INVALID = "WORKFLOW_OBSERVATION_SHAPE_INVALID"
WORKFLOW_PROGRAM_PLAN_BINDING_INVALID = "WORKFLOW_PROGRAM_PLAN_BINDING_INVALID"
WORKFLOW_ROLLBACK_BINDING_INVALID = "WORKFLOW_ROLLBACK_BINDING_INVALID"
WORKFLOW_SLICE_SHAPE_INVALID = "WORKFLOW_SLICE_SHAPE_INVALID"

WorkflowDefinitionFailureCode = Literal[
    "WORKFLOW_ACCEPTANCE_DIGEST_INVALID",
    "WORKFLOW_ACCEPTANCE_INPUT_INVALID",
    "WORKFLOW_CONTRACT_KIND_UNSUPPORTED",
    "WORKFLOW_DSL_COMPILE_FAILURE",
    "WORKFLOW_DSL_CYCLE",
    "WORKFLOW_DSL_DUPLICATE_NODE_ID",
    "WORKFLOW_DSL_MALFORMED_PAYLOAD",
    "WORKFLOW_DSL_MISSING_ENDPOINT",
    "WORKFLOW_DSL_UNSUPPORTED_NODE_TYPE",
    "WORKFLOW_OBSERVATION_SHAPE_INVALID",
    "WORKFLOW_PROGRAM_PLAN_BINDING_INVALID",
    "WORKFLOW_RECEIPT_CONTRACT_INVALID",
    "WORKFLOW_ROLLBACK_BINDING_INVALID",
    "WORKFLOW_SLICE_SHAPE_INVALID",
]

WORKFLOW_DEFINITION_FAILURES = define_failure_family(
    "workflow.definition.failure",
    get_args(WorkflowDefinitionFailureCode),
)


__all__ = [
    "HISTORICAL_C1_ACCEPTANCE_SCHEMA",
    "HISTORICAL_C1_DSL_RECEIPT_SCHEMA",
    "WORKFLOW_ACCEPTANCE_DIGEST_INVALID",
    "WORKFLOW_ACCEPTANCE_INPUT_INVALID",
    "WORKFLOW_ACCEPTANCE_SCHEMA",
    "WORKFLOW_CONTRACT_KIND_UNSUPPORTED",
    "WORKFLOW_DEFINITION_FAILURES",
    "WorkflowDefinitionFailureCode",
    "WORKFLOW_DSL_COMPILE_FAILURE",
    "WORKFLOW_DSL_CYCLE",
    "WORKFLOW_DSL_DUPLICATE_NODE_ID",
    "WORKFLOW_DSL_INPUT_VERSION",
    "WORKFLOW_DSL_MALFORMED_PAYLOAD",
    "WORKFLOW_DSL_MISSING_ENDPOINT",
    "WORKFLOW_DSL_PROGRAM_METADATA_SCHEMA",
    "WORKFLOW_DSL_PROGRAM_SCHEMA",
    "WORKFLOW_DSL_PROJECT_SCOPE_SCHEMA",
    "WORKFLOW_DSL_RECEIPT_SCHEMA",
    "WORKFLOW_DSL_UNSUPPORTED_NODE_TYPE",
    "WORKFLOW_OBSERVATION_SHAPE_INVALID",
    "WORKFLOW_PROGRAM_PLAN_BINDING_INVALID",
    "WORKFLOW_RECEIPT_CONTRACT_INVALID",
    "WORKFLOW_ROLLBACK_BINDING_INVALID",
    "WORKFLOW_SLICE_SHAPE_INVALID",
]
