"""Fixed-public database session and validated project scope identity.

The successor runtime must never reuse the legacy schema-switching project
session.  This module owns the fixed-public session
factory and the server-side ``ProjectScopeRef`` resolver, which is the only
allowed constructor of validated project schema identity.
"""

from __future__ import annotations

import hashlib
import re
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

from sqlalchemy import create_engine, event, select, text
from sqlalchemy.engine import Connection, Engine
from sqlalchemy.orm import Session, sessionmaker

from app.successor_runtime.runtime.ports import ProjectScopeRef

PUBLIC_SEARCH_PATH = "public"
APPLICATION_NAME = "mrw-successor-runtime"
MAX_SCHEMA_IDENTIFIER_BYTES = 63

_SCHEMA_IDENTIFIER_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
_PROJECT_KEY_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
_FORBIDDEN_PROJECT_SCHEMAS = frozenset(
    {
        "public",
        "pg_catalog",
        "information_schema",
        "pg_toast",
        "pg_temp_1",
        "pg_toast_temp_1",
    }
)
_SCOPE_DIGEST_NAMESPACE = b"mrw.project_scope.v2\n"


class ProjectScopeValidationError(ValueError):
    """Raised when a project schema or scope digest is not server-validated."""


@dataclass(frozen=True, slots=True)
class ProjectScopeStale:
    """Observed digest disagreement returned by ``resolve_expected``."""

    project_key: str
    registry_revision: int
    expected_digest: str
    observed_digest: str


@runtime_checkable
class ProjectScopeRegistryReader(Protocol):
    """Read-only public registry boundary used by scope resolution."""

    def current(self, project_key: str) -> Mapping[str, Any]: ...

    def expected(
        self, project_key: str, registry_revision: int
    ) -> Mapping[str, Any]: ...


class PostgresProjectScopeRegistryReader:
    """Exact, fail-closed reader for the public project-scope registry."""

    def __init__(self, connection: Connection) -> None:
        self._connection = connection

    def current(self, project_key: str) -> Mapping[str, Any]:
        from .models import PUBLIC_TABLES

        table = PUBLIC_TABLES["project_scope_registry"]
        rows = self._connection.execute(
            select(table).where(
                table.c.project_key == project_key,
                table.c.state == "ACTIVE",
            )
        ).mappings().all()
        if len(rows) != 1:
            raise ProjectScopeValidationError(
                "project scope registry must contain exactly one ACTIVE row for "
                f"{project_key!r}; observed {len(rows)}"
            )
        return rows[0]

    def expected(
        self, project_key: str, registry_revision: int
    ) -> Mapping[str, Any]:
        from .models import PUBLIC_TABLES

        table = PUBLIC_TABLES["project_scope_registry"]
        rows = self._connection.execute(
            select(table).where(
                table.c.project_key == project_key,
                table.c.registry_revision == registry_revision,
            )
        ).mappings().all()
        if len(rows) != 1:
            raise ProjectScopeValidationError(
                "project scope registry must contain exactly one historical row for "
                f"{project_key!r} revision {registry_revision}; observed {len(rows)}"
            )
        return rows[0]


@runtime_checkable
class ProjectScopeResolver(Protocol):
    """Server-side constructor of validated ``ProjectScopeRef`` values."""

    def resolve(self, authenticated_project_key: str) -> ProjectScopeRef: ...

    def resolve_expected(
        self,
        project_key: str,
        registry_revision: int,
        scope_digest: str,
    ) -> ProjectScopeRef | ProjectScopeStale: ...


def validate_project_key(project_key: str) -> str:
    if (
        not isinstance(project_key, str)
        or _PROJECT_KEY_PATTERN.fullmatch(project_key) is None
    ):
        raise ProjectScopeValidationError(
            f"invalid authenticated project key {project_key!r}"
        )
    return project_key


def validate_project_schema_identifier(schema: str) -> str:
    """Validate a server-resolved project schema identifier.

    Project schema names are generated by the server, never supplied by API
    payloads or transport messages.  The rule keeps names valid PostgreSQL
    identifiers while forbidding control/global schemas.
    """
    if not isinstance(schema, str) or not schema:
        raise ProjectScopeValidationError(
            "project schema identifier must be a non-empty string"
        )
    if len(schema.encode("utf-8")) > MAX_SCHEMA_IDENTIFIER_BYTES:
        raise ProjectScopeValidationError(
            f"project schema identifier {schema!r} exceeds 63 bytes"
        )
    if _SCHEMA_IDENTIFIER_PATTERN.fullmatch(schema) is None:
        raise ProjectScopeValidationError(
            f"project schema identifier {schema!r} is not a valid identifier"
        )
    if schema in _FORBIDDEN_PROJECT_SCHEMAS:
        raise ProjectScopeValidationError(
            f"project schema identifier {schema!r} is reserved"
        )
    return schema


def default_project_schema_name(project_key: str) -> str:
    """Deterministic bootstrap name; runtime resolution still reads registry."""

    validate_project_key(project_key)
    suffix = hashlib.sha256(project_key.encode("utf-8")).hexdigest()[:8]
    return f"mrw_p_{suffix}"


def compute_scope_digest(
    project_key: str,
    resolved_schema: str,
    project_registry_revision: int,
    incarnation: str,
) -> str:
    """Canonical sha256 over the complete project scope binding."""

    validate_project_key(project_key)
    validate_project_schema_identifier(resolved_schema)
    if (
        not isinstance(project_registry_revision, int)
        or isinstance(project_registry_revision, bool)
        or project_registry_revision < 0
    ):
        raise ProjectScopeValidationError(
            "project registry revision must be a non-negative integer"
        )
    if (
        not isinstance(incarnation, str)
        or not incarnation
        or incarnation != incarnation.strip()
        or len(incarnation) > 128
    ):
        raise ProjectScopeValidationError(
            "project scope incarnation must be a non-empty canonical identity"
        )
    payload = (
        _SCOPE_DIGEST_NAMESPACE
        + project_key.encode("utf-8")
        + b"\n"
        + resolved_schema.encode("utf-8")
        + b"\n"
        + str(project_registry_revision).encode("ascii")
        + b"\n"
        + incarnation.encode("utf-8")
    )
    return hashlib.sha256(payload).hexdigest()


def validate_project_scope_ref(scope: ProjectScopeRef) -> ProjectScopeRef:
    """Reject refs that did not come from a validated server binding."""

    if not isinstance(scope, ProjectScopeRef):
        raise ProjectScopeValidationError("expected a ProjectScopeRef")
    validate_project_schema_identifier(scope.resolved_schema)
    expected = compute_scope_digest(
        scope.project_key,
        scope.resolved_schema,
        scope.project_registry_revision,
        scope.incarnation,
    )
    if expected != scope.scope_digest:
        raise ProjectScopeValidationError(
            f"scope digest mismatch for schema {scope.resolved_schema!r}"
        )
    return scope


class ServerProjectScopeResolver:
    """Resolve scope identity only from the authoritative public registry."""

    def __init__(
        self,
        *,
        connection: Connection | None = None,
        registry_reader: ProjectScopeRegistryReader | None = None,
    ) -> None:
        if (connection is None) == (registry_reader is None):
            raise ValueError(
                "ServerProjectScopeResolver requires exactly one of connection "
                "or registry_reader"
            )
        self._registry_reader = (
            PostgresProjectScopeRegistryReader(connection)
            if connection is not None
            else registry_reader
        )

    @staticmethod
    def _ref_from_row(
        row: Mapping[str, Any], *, expected_project_key: str
    ) -> ProjectScopeRef:
        try:
            project_key = validate_project_key(row["project_key"])
            schema = validate_project_schema_identifier(row["resolved_schema"])
            revision = row["registry_revision"]
            incarnation = row["incarnation"]
            stored_digest = row["scope_digest"]
        except (KeyError, TypeError, ValueError) as exc:
            raise ProjectScopeValidationError(
                "project scope registry row is malformed"
            ) from exc
        if project_key != expected_project_key:
            raise ProjectScopeValidationError(
                "project scope registry returned a different project key"
            )
        expected_digest = compute_scope_digest(
            project_key,
            schema,
            revision,
            incarnation,
        )
        if stored_digest != expected_digest:
            raise ProjectScopeValidationError(
                "project scope registry row has an invalid identity digest"
            )
        return ProjectScopeRef(
            project_key=project_key,
            resolved_schema=schema,
            project_registry_revision=revision,
            incarnation=incarnation,
            scope_digest=stored_digest,
        )

    def resolve(self, authenticated_project_key: str) -> ProjectScopeRef:
        project_key = validate_project_key(authenticated_project_key)
        assert self._registry_reader is not None
        return self._ref_from_row(
            self._registry_reader.current(project_key),
            expected_project_key=project_key,
        )

    def resolve_expected(
        self,
        project_key: str,
        registry_revision: int,
        scope_digest: str,
    ) -> ProjectScopeRef | ProjectScopeStale:
        project_key = validate_project_key(project_key)
        if (
            not isinstance(registry_revision, int)
            or isinstance(registry_revision, bool)
            or registry_revision < 0
        ):
            raise ProjectScopeValidationError(
                "project registry revision must be a non-negative integer"
            )
        assert self._registry_reader is not None
        expected = self._ref_from_row(
            self._registry_reader.expected(project_key, registry_revision),
            expected_project_key=project_key,
        )
        if expected.project_registry_revision != registry_revision:
            raise ProjectScopeValidationError(
                "project scope registry returned a different revision"
            )
        if expected.scope_digest != scope_digest:
            return ProjectScopeStale(
                project_key=project_key,
                registry_revision=registry_revision,
                expected_digest=expected.scope_digest,
                observed_digest=scope_digest,
            )
        return expected


def pin_public_search_path(connection: Connection) -> None:
    """Pin the transaction to public without any ContextVar routing."""

    if connection.dialect.name != "postgresql":
        return
    connection.execute(text(f'SET LOCAL search_path TO "{PUBLIC_SEARCH_PATH}"'))


def runtime_connect_args(
    database_url: str,
    *,
    application_name: str = APPLICATION_NAME,
) -> dict[str, Any]:
    """Connect arguments that fix the public schema on PostgreSQL."""

    if "postgresql" not in database_url:
        return {}
    return {
        "options": "-c search_path=public",
        "application_name": application_name,
    }


def create_runtime_engine(
    database_url: str,
    *,
    application_name: str = APPLICATION_NAME,
    pool_pre_ping: bool = True,
    echo: bool = False,
    poolclass: Any = None,
    connect_args: dict[str, Any] | None = None,
    **kwargs: Any,
) -> Engine:
    """Create the fixed-public successor runtime engine."""

    merged_args = runtime_connect_args(
        database_url, application_name=application_name
    )
    if connect_args:
        merged_args = {**merged_args, **connect_args}
    engine_kwargs: dict[str, Any] = {
        "future": True,
        "echo": echo,
        "pool_pre_ping": pool_pre_ping,
    }
    if merged_args:
        engine_kwargs["connect_args"] = merged_args
    if poolclass is not None:
        engine_kwargs["poolclass"] = poolclass
    engine_kwargs.update(kwargs)
    return create_engine(database_url, **engine_kwargs)


class RuntimeSession(Session):
    """ORM session pinned to the public control schema.

    This class gives composition roots an explicit successor runtime session
    identity.  It never reads project ContextVars and never switches
    search_path; project tables are reached through schema-qualified handles.
    """


def create_runtime_session_factory(
    engine: Engine,
    *,
    class_: type[Session] = RuntimeSession,
    **kwargs: Any,
) -> sessionmaker:
    """Return a fixed-public sessionmaker bound to ``engine``."""

    factory = sessionmaker(
        bind=engine,
        class_=class_,
        autoflush=False,
        expire_on_commit=False,
        future=True,
        **kwargs,
    )

    @event.listens_for(factory, "after_begin")
    def _pin_factory_search_path(
        session: Session,
        transaction: Any,
        connection: Connection,
    ) -> None:
        pin_public_search_path(connection)

    return factory


class RuntimeSessionLocal:
    """Fixed-public session factory with the frozen contract name.

    ``RuntimeSessionLocal(engine)`` returns a callable factory; calling it
    creates a ``RuntimeSession`` pinned to the public control schema.
    """

    def __init__(self, engine: Engine, **kwargs: Any) -> None:
        self._factory = create_runtime_session_factory(engine, **kwargs)

    def __call__(self, **kwargs: Any) -> Session:
        return self._factory(**kwargs)
