"""Declarative production observability and canary-stop core."""

from .alerts import (
    AlertDirection,
    AlertEvaluation,
    AlertRule,
    AlertState,
    AlertTransition,
    AlertTransitionReason,
    evaluate_alert_rule,
)
from .contracts import (
    ALERT_DIRECTION,
    ALERT_STATE,
    ALERT_TRANSITION,
    CANARY_ROUTE_ACTION,
    CANARY_ROUTE_DECISION_CONTRACT_VERSION,
    CONTINUITY_REASON,
    METRIC_FAMILY,
    OBSERVABILITY_CONTRACT_VERSION,
    RECEIPT_SCOPE,
    SOURCE_CONTRACT_VERSIONS,
    STOP_REASON,
    ContinuityReason,
    MetricFamily,
    ObservabilityContractVersion,
    PRODUCTION_OBSERVABILITY_RUNTIME_CONTRACT_VERSION,
    PRODUCTION_HTTP_OBSERVATION_CONTRACT_VERSION,
    PRODUCTION_RUNTIME_HEALTH_OBSERVATION_CONTRACT_VERSION,
    ReceiptScope,
    StopReason,
    CanaryRouteAction,
)
from .decision import (
    CanaryRouteDecision,
    ContinueRequest,
    StopRequest,
    decide_canary_route,
)
from .observations import Observation, make_observation, observation_digest
from .health import (
    DatabaseRuntimeSignal,
    ProjectionDriftStatus,
    ProjectionReadStatus,
    ProjectionReleaseStatus,
    ProjectionRuntimeSignal,
    ProviderRuntimeSignal,
    ProviderRuntimeStatus,
    QueueReadStatus,
    QueueRuntimeSignal,
    RuntimeBindingSignal,
    RuntimeBindingStatus,
    RuntimeAuthorityReadSignal,
    RuntimeAuthorityReadStatus,
    RuntimeHealthSnapshot,
)
from .receipts import ObservationReceipt, make_observation_receipt, validate_production_receipt
from .receipts import ReceiptValidationCode
from .config import (
    ProductionObservabilityConfig,
    parse_production_observability_config,
    production_observability_config_from_settings,
)
from .runtime import (
    RUNTIME_PROJECTION_CONTRACT_VERSION,
    RUNTIME_STATE_KEY,
    CanaryRouteAdvice,
    ProductionObservabilityController,
    RuntimeEvaluation,
    install_production_observability,
)

__all__ = [
    "ALERT_DIRECTION",
    "ALERT_STATE",
    "ALERT_TRANSITION",
    "CANARY_ROUTE_ACTION",
    "CANARY_ROUTE_DECISION_CONTRACT_VERSION",
    "CONTINUITY_REASON",
    "METRIC_FAMILY",
    "OBSERVABILITY_CONTRACT_VERSION",
    "PRODUCTION_OBSERVABILITY_RUNTIME_CONTRACT_VERSION",
    "PRODUCTION_HTTP_OBSERVATION_CONTRACT_VERSION",
    "PRODUCTION_RUNTIME_HEALTH_OBSERVATION_CONTRACT_VERSION",
    "RECEIPT_SCOPE",
    "STOP_REASON",
    "AlertDirection",
    "AlertEvaluation",
    "AlertRule",
    "AlertState",
    "AlertTransition",
    "AlertTransitionReason",
    "CanaryRouteAction",
    "CanaryRouteAdvice",
    "CanaryRouteDecision",
    "ContinueRequest",
    "DatabaseRuntimeSignal",
    "MetricFamily",
    "ProjectionDriftStatus",
    "ProjectionReadStatus",
    "ProjectionReleaseStatus",
    "ProjectionRuntimeSignal",
    "ProviderRuntimeSignal",
    "ProviderRuntimeStatus",
    "QueueReadStatus",
    "QueueRuntimeSignal",
    "ObservabilityContractVersion",
    "Observation",
    "ObservationReceipt",
    "ReceiptScope",
    "ReceiptValidationCode",
    "RUNTIME_PROJECTION_CONTRACT_VERSION",
    "RUNTIME_STATE_KEY",
    "StopReason",
    "StopRequest",
    "ContinuityReason",
    "SOURCE_CONTRACT_VERSIONS",
    "decide_canary_route",
    "evaluate_alert_rule",
    "make_observation",
    "make_observation_receipt",
    "ProductionObservabilityConfig",
    "ProductionObservabilityController",
    "RuntimeEvaluation",
    "RuntimeBindingSignal",
    "RuntimeBindingStatus",
    "RuntimeAuthorityReadSignal",
    "RuntimeAuthorityReadStatus",
    "RuntimeHealthSnapshot",
    "install_production_observability",
    "parse_production_observability_config",
    "production_observability_config_from_settings",
    "observation_digest",
    "validate_production_receipt",
]
